In [1]:
import pandas as pd
import functions_simalign

/home/christopher/projects/corpus_tryout/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3291.82it/s]
BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-03-11 12:21:47,247 - simalign.simalign - INFO - Initialized the EmbeddingLoader with model: bert-base-multilingual-cased

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
df_1 = pd.read_csv("extraction_output/annotated_all_part_to_ger.csv").set_index("Unnamed: 0")
df_match_1 = pd.read_csv("extraction_output/adv_ger_matches.csv").set_index("Unnamed: 0")

In [4]:
df_1 = pd.concat([df_1, df_match_1[["best_match", "best_score"]]], axis=1)

In [5]:
df_1.loc[df_1["is_adv_participle"] & df_1["has_gerunziu"]].to_csv(
    "analysis/try_better_matching.csv"
)

In [6]:
df_1 = df_1.loc[df_1["is_adv_participle"] & df_1["has_gerunziu"]]

In [15]:
df_1.head(1)

,1,2,3,4,5,6,7,8,english,lemma,gerunzius_and_lemmas,is_adv_participle,has_gerunziu,best_match,best_score
Unnamed: 0,,,,,,,,,,,,,,,
27,carroll-alenka_v_kraji,"before her was another long passage , and the ...",hurrying,down it .,carroll-alenka_v_kraji,NaN,"înaintea ei se întindea un coridor lung, la ca...",NaN,"before her was another long passage, and the W...",hurry,"[('alergând', 'alerga')]",True,True,alergând,0.152291

In [ ]:
df_1["7"] = df_1["7"].str.replace("ş", "ș").replace("ţ", "ț")
df_1["gerunzius_and_lemmas"] = (
    df_1["gerunzius_and_lemmas"].str.replace("ş", "ș").replace("ţ", "ț") # TODO: this should happen at the very beginning
)

In [13]:
for _, row in df_1.head(1).iterrows():
    print(row["3"])

hurrying

In [50]:
df_1

In [64]:
matching_dict = {}
all_errors = []

In [ ]:
for i, row in df_1.iterrows():
    word_en = row["3"]
    sentence_en = row["english"]
    sentence_ro = row["7"]
    words_ro = [x[0] for x in eval(row["gerunzius_and_lemmas"])]
    truth_value, errors = functions_simalign.is_match(
        word_en=word_en,
        sentence_en=sentence_en,
        word_ro=words_ro,
        sentence_ro=sentence_ro,
    )
    if truth_value or (not truth_value and not errors):
        matching_dict[i] = truth_value
    if errors:
        for error in errors:
            print(f"{error.word=}, {error.sentence=}")
            all_errors.append(errors)

Could not find word -du-se!
error.word='-du-se', error.sentence='Cei trei oșteni umblară o clipă de colo-colo, uitân-du-se după vinovaţii ce trebuiau executaţi, apoi o luară la picior și se alăturară foarte liniștiţi convoiului.'
Could not find word -du-se!
error.word='-du-se', error.sentence='-Asta e foarte IMPORTANT, declară Regele, întorcân-du-se către juraţi.'
Could not find word -du-i-se!
error.word='-du-i-se', error.sentence='Şi totuși, mai știi, urmă, punând hârtia cu versuri pe genunchi și uitându-se chiorâș la ea, dacă stau să mă gândesc, parc-ar avea oarecare înţeles. " DOAR CĂ NU-ÎNOT NU-I BINE. " Nu știi să înoţi, nu-i așa? adăugă, adresân-du-i-se Valetului.'
Could not find word ţindu-mă!
error.word='ţindu-mă', error.sentence='Am coborât scara sim-ţindu-mă caraghioasă.'
Could not find word -nindu-se!
error.word='-nindu-se', error.sentence='-Antricot de mânzat, a răspuns ea spriji-nindu-se în mătură.'
Could not find word ţîndu-și!
error.word='ţîndu-și', error.sentence='Şi cu toate acestea, sus, sus, deasupra orașului, ferestrele noastre luminate auriu trebuie să fi constituit și ele a taină fascinantă, nostalgică, pentru vreun trecător care ar fi ridicat ochii din străzile tot mai întunecate, și puteam să mi-l închipui înălţîndu-și privirile și întrebîndu-se ce se petrece acolo sus.'
Could not find word ascultîn'd!
error.word="ascultîn'd", error.sentence="Astfel că mai în-tîrzie, ascultîn'd o clipă încă vibraţia unei si respiraţie nevăzută."
Could not find word -dînd!
error.word='-dînd', error.sentence='Cu o ultimă privire peste umăr, fetiţa se lăsă, fără entuziasm dar binecrescută, trasă de mînă de guvernantă și împinsă pe ușă tocmai cînd Tom se întorcea în cameră, prece-dînd o tavă cu patru pahare cu gin și cuburi de gheaţă.'
Could not find word -nîndu-se!
error.word='-nîndu-se', error.sentence='La început n-am putut să-mi dau seama de unde veneau cuvintele gemute care răzbăteau cu ecou zgomotos prin încăperea aceasta înaltă și goală — și apoi l-am văzut pe Wilson oprit pe pragul, ridicat cu cîteva trepte, al biroului său, legă-nîndu-se înainte și-napoi și ţinîndu-se cu amîndouă mîinile de pervaz.'
Could not find word watching!
Could not find word watching!
error.word='watching', error.sentence='So I walked away and left him standing there in the moonlight-watching over nothing.'
error.word='watching', error.sentence='So I walked away and left him standing there in the moonlight-watching over nothing.'
Could not find word -cercînd!
error.word='-cercînd', error.sentence='Trase neîndemînatic de cuvertura brodată de pe pat, în-cercînd s-o dea la o parte și se întinse în cele din urmă ţeapăn — adormi pe dată.'
Could not find word -bîndu-l!
error.word='-bîndu-l', error.sentence='Eu ședeam pe geanta mea, pe jos, povestind cu același marinar care fusese în staţia de autobuz din Cheyenne, între-bîndu-l ce se întîmplase cu blonda.'
Could not find word -du-se!
error.word='-du-se', error.sentence='Erau ca omul din temniţa întunecată, de piatră, cu ghiuleaua legată de picior, ridicîn-du-se din subsoluri, hipsterii sordizi ai Americii, o nouă generaţie beat1 căreia mă alăturam în-cet-încet și eu.'
Could not find word -du-se!
error.word='-du-se', error.sentence='Pe treptele caselor de peste drum, simţin-du-se bine și din cînd în cînd privind și la joc, ședeau familii de negri care povesteau și priveau cerul înstelat printre crengile copacilor.'
Could not find word Cînd!
error.word='Cînd', error.sentence='-Cînd banii lui Tom se vor termina, Ed se va întoarce, zise Galatea, privind în cărţi.'
Could not find word ţînd!
error.word='ţînd', error.sentence='Cu strigăte și ochi holbaţi, toţi îl îndemnau pe trompetist să nu se lase, iar el se ghemui și se ridică și suflă din nou, înălţînd sunetul într-un ţipăt subţire deasupra tumultului.'
Could not find word cutînd!
error.word='cutînd', error.sentence='Cînd m-am uitat în jur, am văzut deodată poliţai și oameni care forfoteau în lumina farurilor de la mașina patrulei de poliţie, dis-cutînd despre automobilul furat.'
Could not find word stealing!
error.word='stealing', error.sentence='After investigation, which included corny things like a fatherly quiz, then an abrupt turnabout to frighten me with threats, a comparison of my handwriting, et cetera, and after I made the most magnificent speech of my life to get out of it, concluding with the confession that I was lying about my car-stealing past and was only looking for my paw who was a farmhand hereabouts, he let me go.'
Could not find word -nînd!
error.word='-nînd', error.sentence='Venisem de la Denver, via ferma lui Ed Wall, aproape o mie nouă sute de kilometri, în exact șaptesprezece ore, nepu-nînd la socoteală cele două petrecute în șanţ și cele trei de la fermă și alte două la poliţia din Newton, Iowa. Cred că am avut o medie de o sută zece kilometri la oră, cu un singur șofer, de-a curmezișul întregii ţări.'
Could not find word ţînd!
error.word='ţînd', error.sentence='-Adio, Gregoria ! strigă Dean, trimiţînd o sărutare.'
Could not find word -du-se!
error.word='-du-se', error.sentence='-Ah, mi se frînge inima ! strigă Dean, lovin-du-se în piept.'
Could not find word -indu-și!
error.word='-indu-și', error.sentence='Timp de treizeci de secunde șezuse la masa lui de scris, pipă-indu-și atent scăfârlia cu buricele degetelor și îngrijorându-se.'
Could not find word -du-se!
error.word='-du-se', error.sentence='Frank se uitase atent și îndelung la fiecare în parte, fără comentarii, mulţumin-du-se să clatine din cap.'
Could not find word zicând!
error.word='zicând', error.sentence='Când îi telefonase Vernon, mai la începutul săptămânii, să-și ceară iertare că-l turnase la poliţie-am fost un idiot, stresul, știi, o săptămână de coșmar etc.-și mai ales când îi propusese să-l însoţească la Amsterdam ca să pecetluiască împăcarea (zicând că are, oricum, și el ceva treabă pe acolo), Clive îi răspunsese cu o curtoazie plauzibilă, dar mâinile îi tremuraseră când pusese jos receptorul.'
Could not find word -du-l!
error.word='-du-l', error.sentence='Apoi, cu un prelung, descendent glissando de dezgust, toată secţia de coarde, plus flautele și piculinele, se văluriră înspre alămuri, lăsân-du-l pe criticul muzical-cu produsul stomacului său cu tot, cartofi prăjiţi cu maioneză, consumaţi mai devreme pe Oude Hoogstraat-singur și bine luminat sub un candelabru.'
Could not find word -du-se!
error.word='-du-se', error.sentence='Cu toate acestea, se simţi învăluită de o ușoară tristeţe, în timp ce continua să taie capete, învârtin-du-se în jurul templului, până când nu mai putu fi zărită de pe drum.'
Could not find word -du-se!
error.word='-du-se', error.sentence='Robbie o privi lung pe femeie, pe fata cunoscută de când lumea, gândin-du-se că schimbarea se produsese numai înlăun-trul său și că era la fel de fundamentală-la fel de fundamentală din punct de vedere biologic-ca și nașterea.'
Could not find word vindu-le!
error.word='vindu-le', error.sentence='Plutea deasupra lor, pri-vindu-le neutru, din înalt, împletindu-le distrată cu alte preocupări.'
Could not find word vindu-le!
error.word='vindu-le', error.sentence='Plutea deasupra lor, pri-vindu-le neutru, din înalt, împletindu-le distrată cu alte preocupări.'
Could not find word schimbându-i!
error.word='schimbându-i', error.sentence='Ii auzea încă vocea, felul cum rostise „ Tallis ", pre-schimbându-i numele într-un prenume de fată.'
Could not find word nimicindu-!
error.word='nimicindu-', error.sentence='Parcă era o forţă imensă care te copleșea-ceva ce-ţi pătrundea sub ţeastă, nimicindu-ţi creierul, înfricoșându-te până într-atât încât renunţai la propriile tale păreri, convingându-te, aproape, să negi evidenţa simţurilor.'
Could not find word nimicindu-!
error.word='nimicindu-', error.sentence='Parcă era o forţă imensă care te copleșea-ceva ce-ţi pătrundea sub ţeastă, nimicindu-ţi creierul, înfricoșându-te până într-atât încât renunţai la propriile tale păreri, convingându-te, aproape, să negi evidenţa simţurilor.'
Could not find word nimicindu-!
error.word='nimicindu-', error.sentence='Parcă era o forţă imensă care te copleșea-ceva ce-ţi pătrundea sub ţeastă, nimicindu-ţi creierul, înfricoșându-te până într-atât încât renunţai la propriile tale păreri, convingându-te, aproape, să negi evidenţa simţurilor.'
Could not find word îșnind!
error.word='îșnind', error.sentence='În timp ce Seniorul vorbea, patru șobolani mari se strecuraseră afară din găurile lor și s-au oprit pe labele din spate, ca să-l asculte. Cîinii i-au zărit dintr-o ochire și numai ţîșnind fulgerător înapoi spre găuri au izbutit șobolanii să scape de colţii lor.'
Could not find word -rînd!
error.word='-rînd', error.sentence='Numai și numai din dușmănie neîmpăcată, spe-rînd să ne zădărnicească planurile și să se răzbune pentru expulzarea lui rușinoasă, acest trădător s-a strecurat pînă aici la adăpostul întunericului și al furtunii și a distrus munca noastră de aproape un an.'
Could not find word -cînd!
error.word='-cînd', error.sentence='Cînd se gîndeau cum munciseră, ce clipe de descurajare depășiseră și ce enorme schimbări urmau să intervină în viaţa lor de animale cînd aripile morii aveau să se învîrtească și dinamurile să funcţioneze-cînd se gîndeau la toate aceste lucruri, oboseala li se risipea și zburdau de jur-împrejurul morii de vînt scoţînd strigăte de triumf.'
Could not find word -rînd!
error.word='-rînd', error.sentence='Dar, cînd au văzut steagul verde flutu-rînd la catarg și au auzit pușca trăgînd din nou-de șapte ori a tras în total-, apoi cînd au ascultat discursul lui Napoleon care le felicita pentru conduita lor, animalelor li s-a părut și lor că, la urma urmei, obţinuseră o mare victorie.'
Could not find word urmărindu-!
error.word='urmărindu-', error.sentence='Toate barierele se prăbușiseră înăuntrul său și, urmărindu-1, ascultîndu-1-un om pe care nu-1 cunoșteam, dar în mod evident un om educat care își pierduse complet stăpînirea de sine-mă simţeam ca atunci cînd ești martor la un grav accident de circulaţie, la un incendiu sau o explozie înfiorătoare, o catastrofă publică ale cărei dimensiuni fascinează la fel de tare ca și grotescul ei.'
Could not find word acuzîndu-!
error.word='acuzîndu-', error.sentence='Creîndu-i o imagine falsă, acuzîndu-1 de lucruri pe care nu le făcuse și nu le-ar fi putut face în veci, nu mînjiseră doar o carieră profesională construită cu cea mai mare seriozitate și dăruire, ci îi uciseseră soţia cu care fusese împreună timp de patruzeci de ani.'
Could not find word -du-se!
error.word='-du-se', error.sentence='-Asasinarea ei ! striga Coleman, aplecîn-du-se peste biroul meu și bătînd cu pumnul în el.'
Could not find word gîndu-le!
error.word='gîndu-le', error.sentence='Flossie, mișcă-ţi fundul, ticăloaso "-apucîndu-le de funie, împingîndu-le și înghiontindu-le prin noroiul din curte, apoi în sus o treaptă pînă la padocul pardosit cu ciment, conducîndu-le pe Daisy și pe Maggie prin strungă pînă erau bine legate la par, măsurîndu-le și turnîndu-le porţiile de vitamine și hrană, dezinfectîndu-le și șter-gîndu-le ugerele, apoi dînd drumul laptelui să curgă cu cîteva mișcări iuţi ale mîinii, atașînd de ugerele sterilizate ventuzele de la capătul mulgătoarei, era într-o permanentă mișcare, neclintită în fiecare etapă a procesului, dar, prin contrast cu docilitatea lor încăpăţînată, mișcîndu-se tot timpul cu o agilitate de albină, pînă cînd laptele începea să curgă prin tubul transparent în găleata de oţel inoxidabil, iar ea rămînea în sfîrșit locului, veghind ca totul să funcţioneze și vaca să stea liniștită.'
Could not find word gîndu-le!
error.word='gîndu-le', error.sentence='Flossie, mișcă-ţi fundul, ticăloaso "-apucîndu-le de funie, împingîndu-le și înghiontindu-le prin noroiul din curte, apoi în sus o treaptă pînă la padocul pardosit cu ciment, conducîndu-le pe Daisy și pe Maggie prin strungă pînă erau bine legate la par, măsurîndu-le și turnîndu-le porţiile de vitamine și hrană, dezinfectîndu-le și șter-gîndu-le ugerele, apoi dînd drumul laptelui să curgă cu cîteva mișcări iuţi ale mîinii, atașînd de ugerele sterilizate ventuzele de la capătul mulgătoarei, era într-o permanentă mișcare, neclintită în fiecare etapă a procesului, dar, prin contrast cu docilitatea lor încăpăţînată, mișcîndu-se tot timpul cu o agilitate de albină, pînă cînd laptele începea să curgă prin tubul transparent în găleata de oţel inoxidabil, iar ea rămînea în sfîrșit locului, veghind ca totul să funcţioneze și vaca să stea liniștită.'
Could not find word -rulînd!
error.word='-rulînd', error.sentence='Apoi, chiar pe cînd „ nimicul " Lisei își emana semnificaţia teribilă, Coleman zări o camionetă miscîndu-se pe drumul de asfalt ce se întindea în vale faţă de casă-rulînd încet, o sută sau două de metri, frînînd, pornind din nou, foarte lent, frînînd din nou…'
Could not find word -rulînd!
error.word='-rulînd', error.sentence='Apoi, chiar pe cînd „ nimicul " Lisei își emana semnificaţia teribilă, Coleman zări o camionetă miscîndu-se pe drumul de asfalt ce se întindea în vale faţă de casă-rulînd încet, o sută sau două de metri, frînînd, pornind din nou, foarte lent, frînînd din nou…'
Could not find word privindu-!
error.word='privindu-', error.sentence='Apoi ridică privirea și pe cine vede în pragul ușii, în picioare, privindu-1, dacă nu pe tîmplar? în clipa aceea și-a pierdut cumpătul.'
Could not find word -gînd!
Could not find word -rindu-i!
error.word='-gînd', error.sentence='Ajuns acasă în seara aceea (nici asta n-avea să-și amintească în ce fel) și pînă în orele mici ale dimineţii-cînd a fost nevoie de cinci oameni din brigada de pompieri, cinci camarazi, să-1 reţină, să-1 lege și să-1 expedieze la Northampton-Lester a revăzut totul, absolut totul, acolo, în propria lui casă, îndurînd căldura, îndurînd ploaia, noroiul, furnicile uriașe, albinele ucigașe pe linoleumul lui din bucătărie, lîngă masă, bolnav de diaree, de migrene, bolnav din lipsă de apă și de hrană, fără muniţie, convins că era ultima lui noapte, așteptînd să se întîmple, Foster călcînd pe mină, Quillen înecîndu-se, el însuși aproape înecîndu-se, speriat, azvîrlind grenade în toate părţile și stri-gînd: „ Nu vreau să mor ! ", avioanele de vînătoare amestecate, trăgînd în ele, Drago pierzîndu-și un picior, un braţ, nasul, trupul incinerat al lui Conrity lipindu-i-se de mîini, neputînd convinge un elicopter să aterizeze, elicopterul spunînd că nu putea ateriza pentru că erau atacaţi și el atît de furios, știind că va muri, încît trage în ei, încearcă să doboare un elicopter propriu-cea mai inumană noapte pe care a trăit-o vreodată și care se află acolo, cu el, în casa lui dărăpănată, dar și cea mai lungă noapte, cea mai lungă noapte de pe pămînt și, împietrit de fiecare mișcare pe care o face, camarazi urlînd, făcînd pe ei și plîn-gînd, el însuși nepregătit să audă atîtea plînsete, camarazi loviţi în faţă și murind, inspirînd pentru ultima oară și murind, trupul lui Conrity acope-rindu-i mîinile, Drago sîngerînd peste tot, Lester încercînd să scoale pe cineva din morţi și ţipînd, strigînd fără întrerupere: „ Nu vreau să mor V Moartea nu dă time out.'
error.word='-rindu-i', error.sentence='Ajuns acasă în seara aceea (nici asta n-avea să-și amintească în ce fel) și pînă în orele mici ale dimineţii-cînd a fost nevoie de cinci oameni din brigada de pompieri, cinci camarazi, să-1 reţină, să-1 lege și să-1 expedieze la Northampton-Lester a revăzut totul, absolut totul, acolo, în propria lui casă, îndurînd căldura, îndurînd ploaia, noroiul, furnicile uriașe, albinele ucigașe pe linoleumul lui din bucătărie, lîngă masă, bolnav de diaree, de migrene, bolnav din lipsă de apă și de hrană, fără muniţie, convins că era ultima lui noapte, așteptînd să se întîmple, Foster călcînd pe mină, Quillen înecîndu-se, el însuși aproape înecîndu-se, speriat, azvîrlind grenade în toate părţile și stri-gînd: „ Nu vreau să mor ! ", avioanele de vînătoare amestecate, trăgînd în ele, Drago pierzîndu-și un picior, un braţ, nasul, trupul incinerat al lui Conrity lipindu-i-se de mîini, neputînd convinge un elicopter să aterizeze, elicopterul spunînd că nu putea ateriza pentru că erau atacaţi și el atît de furios, știind că va muri, încît trage în ei, încearcă să doboare un elicopter propriu-cea mai inumană noapte pe care a trăit-o vreodată și care se află acolo, cu el, în casa lui dărăpănată, dar și cea mai lungă noapte, cea mai lungă noapte de pe pămînt și, împietrit de fiecare mișcare pe care o face, camarazi urlînd, făcînd pe ei și plîn-gînd, el însuși nepregătit să audă atîtea plînsete, camarazi loviţi în faţă și murind, inspirînd pentru ultima oară și murind, trupul lui Conrity acope-rindu-i mîinile, Drago sîngerînd peste tot, Lester încercînd să scoale pe cineva din morţi și ţipînd, strigînd fără întrerupere: „ Nu vreau să mor V Moartea nu dă time out.'
Could not find word -gînd!
Could not find word -rindu-i!
error.word='-gînd', error.sentence='Ajuns acasă în seara aceea (nici asta n-avea să-și amintească în ce fel) și pînă în orele mici ale dimineţii-cînd a fost nevoie de cinci oameni din brigada de pompieri, cinci camarazi, să-1 reţină, să-1 lege și să-1 expedieze la Northampton-Lester a revăzut totul, absolut totul, acolo, în propria lui casă, îndurînd căldura, îndurînd ploaia, noroiul, furnicile uriașe, albinele ucigașe pe linoleumul lui din bucătărie, lîngă masă, bolnav de diaree, de migrene, bolnav din lipsă de apă și de hrană, fără muniţie, convins că era ultima lui noapte, așteptînd să se întîmple, Foster călcînd pe mină, Quillen înecîndu-se, el însuși aproape înecîndu-se, speriat, azvîrlind grenade în toate părţile și stri-gînd: „ Nu vreau să mor ! ", avioanele de vînătoare amestecate, trăgînd în ele, Drago pierzîndu-și un picior, un braţ, nasul, trupul incinerat al lui Conrity lipindu-i-se de mîini, neputînd convinge un elicopter să aterizeze, elicopterul spunînd că nu putea ateriza pentru că erau atacaţi și el atît de furios, știind că va muri, încît trage în ei, încearcă să doboare un elicopter propriu-cea mai inumană noapte pe care a trăit-o vreodată și care se află acolo, cu el, în casa lui dărăpănată, dar și cea mai lungă noapte, cea mai lungă noapte de pe pămînt și, împietrit de fiecare mișcare pe care o face, camarazi urlînd, făcînd pe ei și plîn-gînd, el însuși nepregătit să audă atîtea plînsete, camarazi loviţi în faţă și murind, inspirînd pentru ultima oară și murind, trupul lui Conrity acope-rindu-i mîinile, Drago sîngerînd peste tot, Lester încercînd să scoale pe cineva din morţi și ţipînd, strigînd fără întrerupere: „ Nu vreau să mor V Moartea nu dă time out.'

KeyboardInterrupt:

In [21]:
len(errors)

376

In [62]:
errors[25]

('shaking',
 'Frank gazed at each one at length, without comment, simply shaking his head.',
 ['-du'],
 'Frank se uitase atent și îndelung la fiecare în parte, fără comentarii, mulţumin-du-se să clatine din cap.')

In [43]:
functions_simalign.add_pronouns("întinzându", sentence='-Trebuie să-l pui și pe celălalt, a declarat el luând al doilea cercel și întinzându-mi-l.')

'întinzându-mi-l'

In [22]:
len(matching_dict)

4063

In [23]:
matching_df = pd.DataFrame(
    zip(matching_dict.keys(), matching_dict.values()),
    columns=["index", "part_matches_gerunziu"],
).set_index("index")

In [24]:
matching_df

       part_matches_gerunziu
index
27                      True
31                      True
36                      True
65                      True
68                      True
...                      ...
29389                   True
29392                   True
29396                   True
29405                   True
29407                  False

[4063 rows x 1 columns]

In [26]:
df_with_matching = pd.concat([df_1, matching_df], axis=1)

In [29]:
df_with_matching["part_matches_gerunziu"].unique()

array([True, False, nan], dtype=object)

In [34]:
df_with_matching.loc[
    ~(df_with_matching["part_matches_gerunziu"].isna())
    & (df_with_matching["part_matches_gerunziu"] == False)
].sample(10).to_csv("analysis/adv_part_wrong_gerunziu_simalign_sample.csv")

In [ ]:
sentence = "Vorbele ei îi înspăimântă grozav pe cei prezenţi: câteva păsări o tăiară la fugă, în graba mare; o Coţofană bătrână se înfoie în pene, zicând:-Trebuie să pornesc spre casă, nu-mi priește aerul nopţii la gât ! Un Canar își chemă puișorii, zicându-le:-Veniţi iute, dragii mei !"
word = "așteptându"

In [33]:
functions_simalign.add_pronouns(word, sentence)

'zicându-le'

In [14]:
import re

In [15]:
re.split(';|,| ', "this, is a string to;, split")

['this', '', 'is', 'a', 'string', 'to', '', '', 'split']

In [18]:
word = "hurrying"
sentence = "before her was another long passage, and the White Rabbit was still in sight, hurrying down it."

In [21]:
splitting_chars = [" ", ",", ".", ":", ";"]
splitting_string = "|".join(splitting_chars)
words = [w for w in re.split(splitting_string, sentence) if w != ""]

In [25]:
splitting_string

' |,|.|:|;'

In [29]:
re.split(';|,| |\\.', sentence)

['before',
 'her',
 'was',
 'another',
 'long',
 'passage',
 '',
 'and',
 'the',
 'White',
 'Rabbit',
 'was',
 'still',
 'in',
 'sight',
 '',
 'hurrying',
 'down',
 'it',
 '']

In [24]:
re.split(splitting_string, sentence)

['',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '']

In [22]:
words

[]

In [ ]:
re.match(f".*({word}-?[a-zăâîșț]*).*", sentence).group(1)

In [44]:
test_sentence_en = "She return to the middle of the room, wondering how to get out of that place."
test_sentence_ro = "Se întoarse în mijlocul sălii, întrebându-și cum să facă să iasă din acel loc."

In [20]:
import re

In [21]:
word = "întrebându"

In [47]:
matching = re.match(f".*({word}-[a-zăâîșț]*) .*", test_sentence_ro)

In [48]:
matching.group(1)

'întrebându-și'

In [32]:
test_sentence_ro

'Se întoarse în mijlocul sălii, întrebându-se cum să facă să iasă din acel loc.'

In [35]:
print(re.findall("cum", test_sentence_ro))

['cum']

In [19]:
functions_simalign.aligner.get_word_aligns(test_sentence_en, test_sentence_ro)

{'mwmf': [(0, 0),
  (1, 1),
  (2, 2),
  (3, 3),
  (4, 3),
  (5, 3),
  (6, 4),
  (7, 4),
  (8, 5),
  (9, 6),
  (10, 7),
  (11, 10),
  (12, 10),
  (13, 11),
  (14, 12),
  (15, 13)],
 'inter': [(0, 0),
  (2, 2),
  (4, 3),
  (5, 3),
  (7, 4),
  (8, 5),
  (9, 6),
  (10, 7),
  (11, 10),
  (13, 11),
  (14, 12),
  (15, 13)],
 'itermax': [(0, 0),
  (1, 1),
  (2, 2),
  (3, 3),
  (4, 3),
  (5, 3),
  (6, 4),
  (7, 4),
  (8, 5),
  (9, 6),
  (10, 7),
  (10, 9),
  (11, 10),
  (12, 10),
  (13, 11),
  (14, 12),
  (15, 13)]}

In [4]:
df_1 = df_1[df_1["is_adv_participle"]] # only those are of our interest

In [5]:
len(df_1.loc[df_1["has_gerunziu"] & (df_1["best_score"] > 0.117)])

2348

In [6]:
df_1.loc[~(df_1["has_gerunziu"] & (df_1["best_score"] > 0.117))].sample(10).to_csv(
    "analysis/adv_part_no_gerunziu_sample.csv"
)

In [7]:
df_1.loc[(df_1["has_gerunziu"]) & ~(df_1["best_score"] > 0.117)].sample(20).to_csv(
    "analysis/adv_part_wrong_gerunziu_sample.csv"
)

In [8]:
df_1.loc[df_1["has_gerunziu"] & (df_1["best_score"] > 0.12)].to_csv("analysis/part_to_gerunziu.csv")

In [9]:
df_1.loc[~(df_1["has_gerunziu"] & df_1["best_score"] > 0.12)
].sample(20).to_csv("analysis/adv_part_no_gerunziu_sample.csv")

In [10]:
df_2 = pd.read_csv("extraction_output/annotated_all_ger_to_part.csv").set_index("Unnamed: 0")
df_match_2 = pd.read_csv("extraction_output/ger_adv_matches.csv").set_index("Unnamed: 0")

In [11]:
df_2 = pd.concat([df_2, df_match_2[["best_match", "best_score"]]], axis=1)

In [12]:
df_2 = df_2.loc[df_2["is_gerunziu"]] # only those are of our interest

In [13]:
len(df_2)

10413

In [14]:
df_2.loc[(df_2["has_adv_participle"])].head(10)

,1,2,3,4,5,6,7,8,romanian,lemma,adv_parts_and_lemmas,is_gerunziu,has_adv_participle,best_match,best_score
Unnamed: 0,,,,,,,,,,,,,,,
5,carroll-alenka_v_kraji,"înaintea ei se întindea un coridor lung , la c...",alergând,cât îl ţineau picioarele .,carroll-alenka_v_kraji,NaN,"before her was another long passage, and the W...",NaN,"înaintea ei se întindea un coridor lung, la ca...",alerga,"[('hurrying', 'hurry')]",True,True,hurrying,0.152291
7,carroll-alenka_v_kraji,"Şi , după ce- o străbătu în lung şi în lat ,",încercând,"în zadar fiecare uşă în parte , se întoarse în...",carroll-alenka_v_kraji,NaN,and when Alice had been all the way down one s...,NaN,"Şi, după ce-o străbătu în lung şi în lat, înce...",încerca,"[('wondering', 'wonder')]",True,True,wondering,0.035738
8,carroll-alenka_v_kraji,"Şi , după ce- o străbătu în lung şi în lat , î...",întrebându,-se cum să facă să iasă din acel loc .,carroll-alenka_v_kraji,NaN,and when Alice had been all the way down one s...,NaN,"Şi, după ce-o străbătu în lung şi în lat, înce...",întrebându,"[('wondering', 'wonder')]",True,True,wondering,0.153758
10,carroll-alenka_v_kraji,"şi ,",găsind,-o nemaipomenit de bună ( fiindcă avea un gust...,carroll-alenka_v_kraji,NaN,"However, this bottle was not marked ‘poison,’ ...",NaN,"şi, găsind-o nemaipomenit de bună (fiindcă ave...",găsi,"[('finding', 'find')]",True,True,finding,0.461690
14,carroll-alenka_v_kraji,"Nespus de frumos îmbrăcat ,",ţinând,într- o mână o pereche de mănuşi albe din piel...,carroll-alenka_v_kraji,NaN,"It was the White Rabbit returning, splendidly ...",NaN,"Nespus de frumos îmbrăcat, ţinând într-o mână ...",ţinca,"[('muttering', 'mutter')]",True,True,muttering,-0.042773
15,carroll-alenka_v_kraji,Venea tare grăbit şi,bombănind,întruna :,carroll-alenka_v_kraji,NaN,"It was the White Rabbit returning, splendidly ...",NaN,Venea tare grăbit şi bombănind întruna:,bombăni,"[('muttering', 'mutter')]",True,True,muttering,-2.000000
17,carroll-alenka_v_kraji,Alice adună de pe jos mănuşile şi evantaiul şi...,spunându,-şi :,carroll-alenka_v_kraji,NaN,"Alice took up the fan and gloves and, as the h...",NaN,Alice adună de pe jos mănuşile şi evantaiul şi...,spune,"[('talking', 'talk')]",True,True,talking,0.108255
22,carroll-alenka_v_kraji,""" Ce bine ar fi fost de n- aş fi plâns atât ! ...",înotând,şi sirăduindu -se să ajungă la mal .,carroll-alenka_v_kraji,NaN,"‘I wish I hadn’t cried so much !’ said Alice, ...",NaN,""" Ce bine ar fi fost de n-aş fi plâns atât ! ""...",înota,"[('trying', 'try')]",True,True,trying,0.033139
23,carroll-alenka_v_kraji,""" Ce bine ar fi fost de n- aş fi plâns atât ! ...",sirăduindu,-se să ajungă la mal .,carroll-alenka_v_kraji,NaN,"‘I wish I hadn’t cried so much !’ said Alice, ...",NaN,""" Ce bine ar fi fost de n-aş fi plâns atât ! ""...",sirădui,"[('trying', 'try')]",True,True,trying,-2.000000
29,carroll-alenka_v_kraji,"E atât de liniştită , urmă ea cu jumătate de v...",continuând,să înoate leneş prin baltă .,carroll-alenka_v_kraji,NaN,And yet I wish I could show you our cat Dinah....,NaN,"E atât de liniştită, urmă ea cu jumătate de vo...",continua,"[('licking', 'lick')]",True,True,licking,0.055011

In [15]:
len(df_2.loc[(df_2["has_adv_participle"]) & (df_2["best_score"] > 0.11)])

2873

In [18]:
df_2.loc[
    (df_2["has_adv_participle"])
    & (df_2["best_score"] > 0.11)
    & (df_2["best_score"] < 0.12)
].sample(10).to_csv("analysis/score_between_11_12_sample.csv")

In [1]:
df_2.loc[(df_2["has_adv_participle"]) & (df_2["best_score"] > 0.117)].to_csv(
    "analysis/gerunziu_to_part.csv"
)

NameError: name 'df_2' is not defined

In [ ]:
df_ger.loc[(df["has_adv_participle"]) & ~(df_ger["best_score"] > 0.12)].to_csv("analysis/gerund_translated_to")