In [1]:
import pandas as pd
import os
import functions_stanza
import multiprocessing

/home/christopher/projects/corpus_tryout/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-03-10 16:10:36 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json: 439kB [00:00, 18.5MB/s]
2026-03-10 16:10:36 INFO: Downloaded file to /home/christopher/stanza_resources/resources.json
2026-03-10 16:10:38 INFO: Loading these models for language: en (English):
============================================
| Processor    | Package                   |
--------------------------------------------
| tokenize     | combined                  |
| mwt          | combined                  |
| pos          | combined_charlm           |
| lemma        | combined_nocharlm         |
| constituency | ptb3-revised_charlm       |
| depparse     | combined_charlm           |
| sentiment    | sstplus_charlm            |
| ner          | ontonotes-ww-multi_charlm |
============================================

2026-03-10 16:10:38 INFO: Using device: cpu
2026-03-10 16:10:38 INFO: Loading: tokenize
2026-03-10 16:10:39 INFO: Loading: mwt
2026-03-10 16:10:39 INFO: Loading: pos
2026-03-10 16:10:41 INFO: Loading: lemma
2026-03-10 16:10:41 INFO: Loading: constituency
2026-03-10 16:10:42 INFO: Loading: depparse
2026-03-10 16:10:42 INFO: Loading: sentiment
2026-03-10 16:10:42 INFO: Loading: ner
2026-03-10 16:10:44 INFO: Done loading processors!
2026-03-10 16:10:44 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json: 439kB [00:00, 27.1MB/s]
2026-03-10 16:10:44 INFO: Downloaded file to /home/christopher/stanza_resources/resources.json
2026-03-10 16:10:45 INFO: Loading these models for language: ro (Romanian):
============================
| Processor | Package      |
----------------------------
| tokenize  | rrt          |
| pos       | rrt_nocharlm |
| lemma     | rrt_nocharlm |
| depparse  | rrt_nocharlm |
============================

2026-03-10 16:10:45 INFO: Using device: cpu
2026-03-10 16:10:45 INFO: Loading: tokenize
2026-03-10 16:10:45 INFO: Loading: pos
2026-03-10 16:10:46 INFO: Loading: lemma
2026-03-10 16:10:46 INFO: Loading: depparse
2026-03-10 16:10:47 INFO: Done loading processors!

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
dfs = []

for file in os.listdir("ingforms_download"):
    csv = pd.read_csv(f"ingforms_download/{file}", sep=";", header=None)
    csv = csv.set_index(csv[0])
    csv = csv.drop(columns=[0])
    dfs.append(csv)

In [4]:
df = pd.concat(dfs)

In [5]:
df = df.sort_index()

In [6]:
df = df.drop_duplicates().reset_index(drop=True) # remove duplicates; export from kontext pretty iffy

In [7]:
df = df.fillna("")

In [8]:
df["english"] = df[2] + " " + df[3] + " " + df[4]

In [ ]:
replacements = [
    ("‘ ", "‘"),
    (" ’", "’"),
    (" ,", ","),
    (" .", "."),
    (" :", ":"),
    (" ?", "?"),
    ("( ", "("),
    (" )", ")"),
    (" ;", ";"),
    ("' ", "'"),
    (" '", "'"),
    (" -", "-"),
    ("- ", "-"),
    ("ş", "ș"),
    ("ţ", "ț"),  # note: the last two have not been considered in current pickle data!
]

In [10]:
for replacement in replacements:
    df["english"] = df["english"].str.replace(replacement[0], replacement[1])

In [11]:
for replacement in replacements:
    df[7] = df[7].str.replace(replacement[0], replacement[1])

In [12]:
CHUNK_SIZE = 2500

# Parse English

In [14]:
multiprocessing.set_start_method("spawn", force=True)

In [ ]:
process_en = multiprocessing.Process(
    target=functions_stanza.parse_in_chunks, args=(df, "en", "english", "ingforms", CHUNK_SIZE, 9)
)

In [16]:
process_en.start()

2026-03-05 12:37:58 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json: 439kB [00:00, 26.3MB/s]
2026-03-05 12:37:58 INFO: Downloaded file to /home/christopher/stanza_resources/resources.json
2026-03-05 12:37:59 INFO: Loading these models for language: en (English):
============================================
| Processor    | Package                   |
--------------------------------------------
| tokenize     | combined                  |
| mwt          | combined                  |
| pos          | combined_charlm           |
| lemma        | combined_nocharlm         |
| constituency | ptb3-revised_charlm       |
| depparse     | combined_charlm           |
| sentiment    | sstplus_charlm            |
| ner          | ontonotes-ww-multi_charlm |
============================================

2026-03-05 12:37:59 INFO: Using device: cpu
2026-03-05 12:37:59 INFO: Loading: tokenize
2026-03-05 12:38:00 INFO: Loading: mwt
2026-03-05 12:38:00 INFO: Loading: pos
2026-03-05 12:38:01 INFO: Loading: lemma
2026-03-05 12:38:02 INFO: Loading: constituency
2026-03-05 12:38:03 INFO: Loading: depparse
2026-03-05 12:38:03 INFO: Loading: sentiment
2026-03-05 12:38:03 INFO: Loading: ner
2026-03-05 12:38:05 INFO: Done loading processors!
2026-03-05 12:38:05 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json: 439kB [00:00, 26.4MB/s]
2026-03-05 12:38:05 INFO: Downloaded file to /home/christopher/stanza_resources/resources.json
2026-03-05 12:38:06 INFO: Loading these models for language: ro (Romanian):
============================
| Processor | Package      |
----------------------------
| tokenize  | rrt          |
| pos       | rrt_nocharlm |
| lemma     | rrt_nocharlm |
| depparse  | rrt_nocharlm |
============================

2026-03-05 12:38:06 INFO: Using device: cpu
2026-03-05 12:38:06 INFO: Loading: tokenize
2026-03-05 12:38:06 INFO: Loading: pos
2026-03-05 12:38:07 INFO: Loading: lemma
2026-03-05 12:38:07 INFO: Loading: depparse
2026-03-05 12:38:08 INFO: Done loading processors!

Parsing chunk 20000 to 22499

In [17]:
multiprocessing.active_children()

In [13]:
parsed_dict_en = functions_stanza.load_pickled_data(folder="ingforms", language="en")

parsed_slice_en_27500_29414.pkl
parsed_slice_en_17500_19999.pkl
parsed_slice_ro_20000_22499.pkl
parsed_slice_en_7500_9999.pkl
parsed_slice_ro_17500_19999.pkl
parsed_slice_ro_10000_12499.pkl
parsed_slice_en_20000_22499.pkl
parsed_slice_ro_0_2499.pkl
parsed_slice_ro_15000_17499.pkl
parsed_slice_en_12500_14999.pkl
parsed_slice_en_2500_4999.pkl
parsed_slice_ro_5000_7499.pkl
parsed_slice_ro_25000_27499.pkl
parsed_slice_en_10000_12499.pkl
parsed_slice_en_25000_27499.pkl
parsed_slice_ro_22500_24999.pkl
parsed_slice_ro_12500_14999.pkl
parsed_slice_en_0_2499.pkl
parsed_slice_ro_27500_29414.pkl
parsed_slice_ro_7500_9999.pkl
parsed_slice_en_22500_24999.pkl
parsed_slice_ro_2500_4999.pkl
parsed_slice_en_15000_17499.pkl
parsed_slice_en_5000_7499.pkl

In [14]:
adv_part_indices_and_lemmas = []

In [15]:
number = 1

for i in range(0, len(df)):
    row = df.iloc[i]
    contains_adv_part, lemma_of_adv_part = functions_stanza.sentences_contain_adv_part(
        row[3], parsed_dict_en[i]
    )
    if contains_adv_part:
        adv_part_indices_and_lemmas.append((i, lemma_of_adv_part))

{
  "id": 17,
  "text": "hurrying",
  "lemma": "hurry",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 15,
  "deprel": "advcl",
  "start_char": 6962,
  "end_char": 6970
}
{
  "id": 28,
  "text": "wondering",
  "lemma": "wonder",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 22,
  "deprel": "advcl",
  "start_char": 7754,
  "end_char": 7763
}
{
  "id": 21,
  "text": "finding",
  "lemma": "find",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 63,
  "deprel": "advcl",
  "start_char": 9418,
  "end_char": 9425
}
{
  "id": 5,
  "text": "finding",
  "lemma": "find",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 12,
  "deprel": "advcl",
  "start_char": 10220,
  "end_char": 10227
}
{
  "id": 9,
  "text": "sending",
  "lemma": "send",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 7,
  "deprel": "advcl",
  "start_char": 13420,
  "end_char": 13427
}
{
  "id": 10,
  "text": "lying",
  "lemma": "lie",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 4,
  "deprel": "advcl",
  "start_char": 13587,
  "end_char": 13592
}
{
  "id": 37,
  "text": "muttering",
  "lemma": "mutter",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 30,
  "deprel": "advcl",
  "start_char": 15078,
  "end_char": 15087
}
{
  "id": 27,
  "text": "talking",
  "lemma": "talk",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 25,
  "deprel": "advcl",
  "start_char": 15519,
  "end_char": 15526
}
{
  "id": 19,
  "text": "trying",
  "lemma": "try",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 11,
  "deprel": "advcl",
  "start_char": 18820,
  "end_char": 18826
}
{
  "id": 38,
  "text": "licking",
  "lemma": "lick",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 31,
  "deprel": "advcl",
  "start_char": 20300,
  "end_char": 20307
}
{
  "id": 15,
  "text": "turning",
  "lemma": "turn",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 13,
  "deprel": "advcl",
  "start_char": 24278,
  "end_char": 24285
}
{
  "id": 12,
  "text": "rising",
  "lemma": "rise",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 7,
  "deprel": "advcl",
  "start_char": 24378,
  "end_char": 24384
}
{
  "id": 14,
  "text": "pointing",
  "lemma": "point",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 10,
  "deprel": "advcl",
  "start_char": 25611,
  "end_char": 25619
}
{
  "id": 11,
  "text": "calling",
  "lemma": "call",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 7,
  "deprel": "advcl",
  "start_char": 25723,
  "end_char": 25730
}
{
  "id": 5,
  "text": "turning",
  "lemma": "turn",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 2,
  "deprel": "advcl",
  "start_char": 25847,
  "end_char": 25854
}
{
  "id": 18,
  "text": "saying",
  "lemma": "say",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 14,
  "deprel": "advcl",
  "start_char": 25985,
  "end_char": 25991
}
{
  "id": 22,
  "text": "looking",
  "lemma": "look",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 18,
  "deprel": "advcl",
  "start_char": 26160,
  "end_char": 26167
}
{
  "id": 15,
  "text": "turning",
  "lemma": "turn",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 11,
  "deprel": "advcl",
  "start_char": 26272,
  "end_char": 26279
}
{
  "id": 14,
  "text": "looking",
  "lemma": "look",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 11,
  "deprel": "advcl",
  "start_char": 26488,
  "end_char": 26495
}
{
  "id": 15,
  "text": "getting",
  "lemma": "get",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 11,
  "deprel": "advcl",
  "start_char": 27091,
  "end_char": 27098
}
{
  "id": 19,
  "text": "addressing",
  "lemma": "address",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 15,
  "deprel": "advcl",
  "start_char": 27503,
  "end_char": 27513
}
{
  "id": 20,
  "text": "remarking",
  "lemma": "remark",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 14,
  "deprel": "advcl",
  "start_char": 27923,
  "end_char": 27932
}
{
  "id": 27,
  "text": "hoping",
  "lemma": "hope",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 22,
  "deprel": "advcl",
  "start_char": 28442,
  "end_char": 28448
}
{
  "id": 7,
  "text": "trotting",
  "lemma": "trot",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 5,
  "deprel": "advcl",
  "start_char": 28822,
  "end_char": 28830
}
{
  "id": 8,
  "text": "saying",
  "lemma": "say",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 3,
  "deprel": "advcl",
  "start_char": 31761,
  "end_char": 31767
}
{
  "id": 7,
  "text": "taking",
  "lemma": "take",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 4,
  "deprel": "advcl",
  "start_char": 33447,
  "end_char": 33453
}
{
  "id": 23,
  "text": "forgetting",
  "lemma": "forget",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 15,
  "deprel": "advcl",
  "start_char": 34058,
  "end_char": 34068
}
{
  "id": 33,
  "text": "scratching",
  "lemma": "scratch",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 18,
  "deprel": "advcl",
  "start_char": 35360,
  "end_char": 35370
}
{
  "id": 46,
  "text": "saying",
  "lemma": "say",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 33,
  "deprel": "advcl",
  "start_char": 36110,
  "end_char": 36116
}
{
  "id": 21,
  "text": "trying",
  "lemma": "try",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 16,
  "deprel": "advcl",
  "start_char": 37929,
  "end_char": 37935
}
{
  "id": 2,
  "text": "knowing",
  "lemma": "know",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 8,
  "deprel": "advcl",
  "start_char": 38107,
  "end_char": 38114
}
{
  "id": 4,
  "text": "thinking",
  "lemma": "think",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 31,
  "deprel": "advcl",
  "start_char": 38238,
  "end_char": 38246
}
{
  "id": 14,
  "text": "running",
  "lemma": "run",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 4,
  "deprel": "advcl",
  "start_char": 38875,
  "end_char": 38882
}
{
  "id": 42,
  "text": "smoking",
  "lemma": "smoke",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 39,
  "deprel": "advcl",
  "start_char": 40921,
  "end_char": 40928
}
{
  "id": 10,
  "text": "making",
  "lemma": "make",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 2,
  "deprel": "advcl",
  "start_char": 41405,
  "end_char": 41411
}
{
  "id": 10,
  "text": "swallowing",
  "lemma": "swallow",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 7,
  "deprel": "advcl",
  "start_char": 41593,
  "end_char": 41603
}
{
  "id": 15,
  "text": "rearing",
  "lemma": "rear",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 10,
  "deprel": "advcl",
  "start_char": 42445,
  "end_char": 42452
}
{
  "id": 17,
  "text": "remarking",
  "lemma": "remark",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 10,
  "deprel": "advcl",
  "start_char": 42714,
  "end_char": 42723
}
{
  "id": 12,
  "text": "trying",
  "lemma": "try",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 2,
  "deprel": "advcl",
  "start_char": 43065,
  "end_char": 43071
}
{
  "id": 9,
  "text": "hatching",
  "lemma": "hatch",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 7,
  "deprel": "advcl",
  "start_char": 45604,
  "end_char": 45612
}
{
  "id": 20,
  "text": "raising",
  "lemma": "raise",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 16,
  "deprel": "advcl",
  "start_char": 45865,
  "end_char": 45872
}
{
  "id": 26,
  "text": "nibbling",
  "lemma": "nibble",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 22,
  "deprel": "advcl",
  "start_char": 47597,
  "end_char": 47605
}
{
  "id": 48,
  "text": "judging",
  "lemma": "judge",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 57,
  "deprel": "advcl",
  "start_char": 50179,
  "end_char": 50186
}
{
  "id": 31,
  "text": "saying",
  "lemma": "say",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 25,
  "deprel": "advcl",
  "start_char": 50666,
  "end_char": 50672
}
{
  "id": 14,
  "text": "changing",
  "lemma": "change",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 5,
  "deprel": "advcl",
  "start_char": 50797,
  "end_char": 50805
}
{
  "id": 26,
  "text": "staring",
  "lemma": "stare",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 18,
  "deprel": "advcl",
  "start_char": 51303,
  "end_char": 51310
}
{
  "id": 36,
  "text": "nursing",
  "lemma": "nurse",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 25,
  "deprel": "advcl",
  "start_char": 53154,
  "end_char": 53161
}
{
  "id": 9,
  "text": "stirring",
  "lemma": "stir",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 4,
  "deprel": "advcl",
  "start_char": 53361,
  "end_char": 53369
}
{
  "id": 6,
  "text": "feeling",
  "lemma": "feel",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 2,
  "deprel": "advcl",
  "start_char": 54193,
  "end_char": 54200
}
{
  "id": 14,
  "text": "jumping",
  "lemma": "jump",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 11,
  "deprel": "advcl",
  "start_char": 55057,
  "end_char": 55064
}
{
  "id": 21,
  "text": "flinging",
  "lemma": "fling",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 17,
  "deprel": "advcl",
  "start_char": 56462,
  "end_char": 56470
}
{
  "id": 11,
  "text": "waving",
  "lemma": "wave",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 18,
  "deprel": "advcl",
  "start_char": 59697,
  "end_char": 59703
}
{
  "id": 11,
  "text": "waving",
  "lemma": "wave",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 18,
  "deprel": "advcl",
  "start_char": 59874,
  "end_char": 59880
}
{
  "id": 7,
  "text": "expecting",
  "lemma": "expect",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 2,
  "deprel": "advcl",
  "start_char": 60554,
  "end_char": 60563
}
{
  "id": 17,
  "text": "sitting",
  "lemma": "sit",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 12,
  "deprel": "advcl",
  "start_char": 60968,
  "end_char": 60975
}
{
  "id": 9,
  "text": "beginning",
  "lemma": "begin",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 5,
  "deprel": "advcl",
  "start_char": 61317,
  "end_char": 61326
}
{
  "id": 50,
  "text": "resting",
  "lemma": "rest",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 44,
  "deprel": "advcl",
  "start_char": 63392,
  "end_char": 63399
}
{
  "id": 4,
  "text": "turning",
  "lemma": "turn",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 2,
  "deprel": "advcl",
  "start_char": 64458,
  "end_char": 64465
}
{
  "id": 25,
  "text": "shaking",
  "lemma": "shake",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 20,
  "deprel": "advcl",
  "start_char": 64990,
  "end_char": 64997
}
{
  "id": 15,
  "text": "looking",
  "lemma": "look",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 13,
  "deprel": "advcl",
  "start_char": 65354,
  "end_char": 65361
}
{
  "id": 5,
  "text": "turning",
  "lemma": "turn",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 3,
  "deprel": "advcl",
  "start_char": 65905,
  "end_char": 65912
}
{
  "id": 12,
  "text": "tossing",
  "lemma": "toss",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 10,
  "deprel": "advcl",
  "start_char": 66271,
  "end_char": 66278
}
{
  "id": 14,
  "text": "yawning",
  "lemma": "yawn",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 12,
  "deprel": "advcl",
  "start_char": 67222,
  "end_char": 67229
}
{
  "id": 12,
  "text": "forgetting",
  "lemma": "forget",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 8,
  "deprel": "advcl",
  "start_char": 68336,
  "end_char": 68346
}
{
  "id": 17,
  "text": "choosing",
  "lemma": "choose",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 11,
  "deprel": "advcl",
  "start_char": 68549,
  "end_char": 68557
}
{
  "id": 14,
  "text": "yawning",
  "lemma": "yawn",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 11,
  "deprel": "advcl",
  "start_char": 68949,
  "end_char": 68956
}
{
  "id": 29,
  "text": "hoping",
  "lemma": "hope",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 22,
  "deprel": "advcl",
  "start_char": 69870,
  "end_char": 69876
}
{
  "id": 31,
  "text": "painting",
  "lemma": "paint",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 24,
  "deprel": "advcl",
  "start_char": 71423,
  "end_char": 71431
}
{
  "id": 29,
  "text": "smiling",
  "lemma": "smile",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 22,
  "deprel": "advcl",
  "start_char": 72881,
  "end_char": 72888
}
{
  "id": 8,
  "text": "carrying",
  "lemma": "carry",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 2,
  "deprel": "advcl",
  "start_char": 73259,
  "end_char": 73267
}
{
  "id": 8,
  "text": "tossing",
  "lemma": "toss",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 4,
  "deprel": "advcl",
  "start_char": 73370,
  "end_char": 73377
}
{
  "id": 3,
  "text": "turning",
  "lemma": "turn",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 8,
  "deprel": "advcl",
  "start_char": 73435,
  "end_char": 73442
}
{
  "id": 12,
  "text": "pointing",
  "lemma": "point",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 8,
  "deprel": "advcl",
  "start_char": 73560,
  "end_char": 73568
}
{
  "id": 4,
  "text": "turning",
  "lemma": "turn",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 12,
  "deprel": "advcl",
  "start_char": 74418,
  "end_char": 74425
}
{
  "id": 18,
  "text": "going",
  "lemma": "go",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 9,
  "deprel": "advcl",
  "start_char": 74695,
  "end_char": 74700
}
{
  "id": 12,
  "text": "looking",
  "lemma": "look",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 4,
  "deprel": "advcl",
  "start_char": 75275,
  "end_char": 75282
}
{
  "id": 17,
  "text": "wondering",
  "lemma": "wonder",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 13,
  "deprel": "advcl",
  "start_char": 75439,
  "end_char": 75448
}
{
  "id": 25,
  "text": "tumbling",
  "lemma": "tumble",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 19,
  "deprel": "advcl",
  "start_char": 76019,
  "end_char": 76027
}
{
  "id": 25,
  "text": "feeling",
  "lemma": "feel",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 18,
  "deprel": "advcl",
  "start_char": 87633,
  "end_char": 87640
}
{
  "id": 13,
  "text": "listening",
  "lemma": "listen",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 9,
  "deprel": "advcl",
  "start_char": 88482,
  "end_char": 88491
}
{
  "id": 13,
  "text": "coming",
  "lemma": "come",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 9,
  "deprel": "advcl",
  "start_char": 88971,
  "end_char": 88977
}
{
  "id": 30,
  "text": "screaming",
  "lemma": "scream",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 21,
  "deprel": "advcl",
  "start_char": 89868,
  "end_char": 89877
}
{
  "id": 12,
  "text": "looking",
  "lemma": "look",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 7,
  "deprel": "advcl",
  "start_char": 91714,
  "end_char": 91721
}
{
  "id": 13,
  "text": "digging",
  "lemma": "digg",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 9,
  "deprel": "advcl",
  "start_char": 92474,
  "end_char": 92481
}
{
  "id": 12,
  "text": "feeling",
  "lemma": "feel",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 9,
  "deprel": "advcl",
  "start_char": 92997,
  "end_char": 93004
}
{
  "id": 20,
  "text": "frowning",
  "lemma": "frown",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 18,
  "deprel": "advcl",
  "start_char": 93474,
  "end_char": 93482
}
{
  "id": 15,
  "text": "stamping",
  "lemma": "stamp",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 11,
  "deprel": "advcl",
  "start_char": 93585,
  "end_char": 93593
}
{
  "id": 38,
  "text": "remarking",
  "lemma": "remark",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 29,
  "deprel": "advcl",
  "start_char": 94091,
  "end_char": 94100
}
{
  "id": 9,
  "text": "lying",
  "lemma": "lie",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 4,
  "deprel": "advcl",
  "start_char": 94764,
  "end_char": 94769
}
{
  "id": 6,
  "text": "leaving",
  "lemma": "leave",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 3,
  "deprel": "advcl",
  "start_char": 94844,
  "end_char": 94851
}
{
  "id": 16,
  "text": "sitting",
  "lemma": "sit",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 4,
  "deprel": "advcl",
  "start_char": 94983,
  "end_char": 94990
}
{
  "id": 14,
  "text": "counting",
  "lemma": "count",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 12,
  "deprel": "advcl",
  "start_char": 96793,
  "end_char": 96801
}
{
  "id": 15,
  "text": "sighing",
  "lemma": "sigh",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 11,
  "deprel": "advcl",
  "start_char": 98059,
  "end_char": 98066
}
{
  "id": 14,
  "text": "capering",
  "lemma": "caper",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 9,
  "deprel": "advcl",
  "start_char": 98602,
  "end_char": 98610
}
{
  "id": 22,
  "text": "dropping",
  "lemma": "drop",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 16,
  "deprel": "advcl",
  "start_char": 98741,
  "end_char": 98749
}
{
  "id": 18,
  "text": "feeling",
  "lemma": "feel",
  "upos": "VERB",
  "xpos": "VBG",
  "feats": "Tense=Pres|VerbForm=Part",
  "head": 15,
  "deprel": "advcl",
  "start_char": 99899,
  "end_char": 99906
}
{
  "id": 12,

In [16]:
adv_part_indices_and_lemmas

[(27, 'hurry'),
 (31, 'wonder'),
 (36, 'find'),
 (41, 'find'),
 (56, 'send'),
 (58, 'lie'),
 (65, 'mutter'),
 (68, 'talk'),
 (83, 'try'),
 (89, 'lick'),
 (105, 'turn'),
 (106, 'rise'),
 (112, 'point'),
 (113, 'call'),
 (114, 'turn'),
 (115, 'say'),
 (116, 'look'),
 (117, 'turn'),
 (119, 'look'),
 (124, 'get'),
 (128, 'address'),
 (131, 'remark'),
 (134, 'hope'),
 (136, 'trot'),
 (152, 'say'),
 (159, 'take'),
 (162, 'forget'),
 (171, 'scratch'),
 (173, 'say'),
 (184, 'try'),
 (186, 'know'),
 (187, 'think'),
 (190, 'run'),
 (198, 'smoke'),
 (200, 'make'),
 (201, 'swallow'),
 (207, 'rear'),
 (209, 'remark'),
 (211, 'try'),
 (222, 'hatch'),
 (224, 'raise'),
 (234, 'nibble'),
 (244, 'judge'),
 (246, 'say'),
 (247, 'change'),
 (250, 'stare'),
 (262, 'nurse'),
 (264, 'stir'),
 (270, 'feel'),
 (275, 'jump'),
 (284, 'fling'),
 (299, 'wave'),
 (300, 'wave'),
 (306, 'expect'),
 (308, 'sit'),
 (311, 'begin'),
 (318, 'rest'),
 (326, 'turn'),
 (328, 'shake'),
 (330, 'look'),
 (334, 'turn'),
 (337, 'toss'),
 (344, 'yawn'),
 (354, 'forget'),
 (356, 'choose'),
 (359, 'yawn'),
 (364, 'hope'),
 (371, 'paint'),
 (381, 'smile'),
 (383, 'carry'),
 (384, 'toss'),
 (385, 'turn'),
 (386, 'point'),
 (391, 'turn'),
 (393, 'go'),
 (397, 'look'),
 (398, 'wonder'),
 (402, 'tumble'),
 (424, 'feel'),
 (428, 'listen'),
 (431, 'come'),
 (437, 'scream'),
 (444, 'look'),
 (450, 'digg'),
 (453, 'feel'),
 (457, 'frown'),
 (458, 'stamp'),
 (460, 'remark'),
 (464, 'lie'),
 (465, 'leave'),
 (466, 'sit'),
 (478, 'count'),
 (482, 'sigh'),
 (486, 'caper'),
 (487, 'drop'),
 (494, 'feel'),
 (504, 'wonder'),
 (510, 'take'),
 (524, 'turn'),
 (527, 'look'),
 (536, 'look'),
 (542, 'get'),
 (543, 'feel'),
 (544, 'forget'),
 (545, 'upsetting'),
 (547, 'remind'),
 (550, 'look'),
 (552, 'gaze'),
 (553, 'turn'),
 (560, 'jump'),
 (561, 'rub'),
 (563, 'spread'),
 (565, 'turn'),
 (567, 'point'),
 (568, 'throw'),
 (570, 'use'),
 (572, 'look'),
 (574, 'turn'),
 (580, 'think'),
 (581, 'lean'),
 (582, 'watch'),
 (596, 'remember'),
 (607, 'dart'),
 (609, 'knock'),
 (610, 'make'),
 (611, 'polish'),
 (616, 'study'),
 (617, 'indicate'),
 (629, 'fire'),
 (631, 'take'),
 (639, 'think'),
 (640, 'know'),
 (645, 'feel'),
 (648, 'cover'),
 (651, 'carry'),
 (656, 'move'),
 (661, 'take'),
 (663, 'look'),
 (665, 'walk'),
 (666, 'separate'),
 (672, 'catching'),
 (673, 'dart'),
 (675, 'popp'),
 (676, 'leave'),
 (682, 'gaze'),
 (683, 'clutch'),
 (684, 'wrestle'),
 (685, 'smoke'),
 (697, 'think'),
 (714, 'wipe'),
 (715, 'extend'),
 (723, 'turn'),
 (725, 'hope'),
 (734, 'bounce'),
 (735, 'order'),
 (737, 'look'),
 (760, 'change'),
 (763, 'wait'),
 (765, 'turn'),
 (767, 'cut'),
 (768, 'join'),
 (769, 'stand'),
 (770, 'wear'),
 (774, 'irone'),
 (776, 'stop'),
 (777, 'come'),
 (781, 'watch'),
 (790, 'study'),
 (792, 'have'),
 (794, 'climb'),
 (795, 'hold'),
 (797, 'edg'),
 (800, 'wait'),
 (802, 'peek'),
 (805, 'make'),
 (806, 'touch'),
 (807, 'polish'),
 (810, 'hope'),
 (815, 'try'),
 (817, 'wear'),
 (818, 'fall'),
 (821, 'hold'),
 (830, 'help'),
 (831, 'glance'),
 (841, 'leave'),
 (845, 'become'),
 (849, 'frame'),
 (851, 'keep'),
 (852, 'lay'),
 (853, 'try'),
 (854, 'return'),
 (856, 'feed'),
 (871, 'chuckle'),
 (872, 'talk'),
 (880, 'wait'),
 (887, 'pick'),
 (889, 'think'),
 (896, 'divide'),
 (897, 'feel'),
 (898, 'jump'),
 (900, 'grab'),
 (902, 'hold'),
 (903, 'feel'),
 (910, 'say'),
 (913, 'sit'),
 (919, 'gaze'),
 (925, 'brighten'),
 (928, 'look'),
 (929, 'buy'),
 (930, 'change'),
 (937, 'stroke'),
 (941, 'adjust'),
 (944, 'press'),
 (947, 'watch'),
 (951, 'look'),
 (953, 'join'),
 (954, 'sample'),
 (964, 'shake'),
 (966, 'breathe'),
 (969, 'hold'),
 (971, 'chuckle'),
 (976, 'glance'),
 (977, 'dust'),
 (978, 'move'),
 (981, 'wear'),
 (986, 'place'),
 (989, 'tread'),
 (993, 'try'),
 (996, 'close'),
 (1004, 'close'),
 (1006, 'emerge'),
 (1014, 'wait'),
 (1030, 'maintain'),
 (1033, 'hold'),
 (1034, 'feel'),
 (1038, 'stop'),
 (1039, 'smile'),
 (1044, 'tell'),
 (1048, 'rub'),
 (1059, 'cradl'),
 (1063, 'try'),
 (1067, 'clean'),
 (1068, 'want'),
 (1074, 'straighten'),
 (1081, 'straighten'),
 (1085, 'work'),
 (1086, 'listen'),
 (1088, 'lean'),
 (1091, 'ignore'),
 (1095, 'hang'),
 (1096, 'shift'),
 (1097, 'try'),
 (1099, 'leave'),
 (1102, 'leave'),
 (1104, 'push'),
 (1108, 'cheer'),
 (1114, 'hope'),
 (1122, 'hold'),
 (1123, 'cradl'),
 (1125, 'gaze'),
 (1129, 'squirm'),
 (1131, 'thank'),
 (1139, 'know'),
 (1150, 'spill'),
 (1151, 'nodd'),
 (1154, 'pull'),
 (1157, 'drink'),
 (1160, 'call'),
 (1161, 'bring'),
 (1162, 'talk'),
 (1164, 'lean'),
 (1165, 'pull'),
 (1168, 'hold'),
 (1169, 'lean'),
 (1171, 'demand'),
 (1172, 'help'),
 (1184, 'wait'),
 (1189, 'drop'),
 (1195, 'hunch'),
 (1196, 'wait'),
 (1206, 'frown'),
 (1210, 'turn'),
 (1214, 'stir'),
 (1217, 'sharpen'),
 (1221, 'side'),
 (1237, 'watch'),
 (1238, 'smile'),
 (1240, 'think'),
 (1246, 'open'),
 (1248, 'measure'),
 (1254, 'leave'),
 (1256, 'remove'),
 (1257, 'choose'),
 (1258, 'look'),
 (1259, 'look'),
 (1261, 'name'),
 (1272, 'shift'),
 (1274, 'anchor'),
 (1277, 'use'),
 (1283, 'fill'),
 (1290, 'hold'),
 (1292, 'dropp'),
 (1293, 'place'),
 (1295, 'have'),
 (1300, 'leave'),
 (1303, 'put'),
 (1307, 'complain'),
 (1312, 'hold'),
 (1350, 'hold'),
 (1351, 'sit'),
 (1353, 'teach'),
 (1355, 'fetch'),
 (1359, 'look'),
 (1362, 'slide'),
 (1363, 'press'),
 (1377, 'swear'),
 (1378, 'spill'),
 (1381, 'refuse'),
 (1396, 'fall'),
 (1404, 'watch'),
 (1407, 'know'),
 (1416, 'smooth'),
 (1417, 'press'),
 (1418, 'turn'),
 (1420, 'ignore'),
 (1421, 'meet'),
 (1434, 'add'),
 (1435, 'tell'),
 (1436, 'describe'),
 (1441, 'remove'),
 (1447, 'prefer'),
 (1449, 'sort'),
 (1453, 'climb'),
 (1454, 'look'),
 (1456, 'expect'),
 (1460, 'chuckle'),
 (1465, 'say'),
 (1472, 'see'),
 (1474, 'grasp'),
 (1475, 'lean'),
 (1476, 'rest'),
 (1478, 'write'),
 (1479, 'play'),
 (1486, 'lean'),
 (1493, 'linger'),
 (1496, 'continue'),
 (1502, 'wait'),
 (1503, 'set'),
 (1504, 'relin'),
 (1505, 'replace'),
 (1507, 'replace'),
 (1511, 'hope'),
 (1518, 'smile'),
 (1523, 'wipe'),
 (1528, 'ignore'),
 (1529, 'write'),
 (1531, 'hang'),
 (1545, 'tap'),
 (1549, 'think'),
 (1553, 'steal'),
 (1557, 'lose'),
 (1558, 'prefer'),
 (1566, 'scrubb'),
 (1577, 'watch'),
 (1579, 'separate'),
 (1585, 'come'),
 (1592, 'tinge'),
 (1595, 'leave'),
 (1599, 'hold'),
 (1602, 'sit'),
 (1603, 'climb'),
 (1615, 'look'),
 (1617, 'try'),
 (1618, 'lock'),
 (1620, 'send'),
 (1621, 'treat'),
 (1635, 'place'),
 (1640, 'listen'),
 (1642, 'leave'),
 (1651, 'go'),
 (1654, 'weigh'),
 (1659, 'pour'),
 (1664, 'tap'),
 (1666, 'count'),
 (1676, 'hide'),
 (1677, 'check'),
 (1678, 'ignore'),
 (1691, 'ask'),
 (1702, 'disappear'),
 (1707, 'leave'),
 (1708, 'housing'),
 (1723, 'force'),
 (1724, 'turn'),
 (1733, 'feel'),
 (1735, 'look'),
 (1737, 'wear'),
 (1753, 'play'),
 (1773, 'turn'),
 (1776, 'blot'),
 (1779, 'hand'),
 (1786, 'pour'),
 (1788, 'fold'),
 (1800, 'face'),
 (1802, 'remember'),
 (1812, 'look'),
 (1816, 'tuck'),
 (1818, 'shut'),
 (1819, 'crisscross'),
 (1820, 'check'),
 (1822, 'finish'),
 (1824, 'cover'),
 (1829, 'look'),
 (1848, 'lean'),
 (1849, 'grab'),
 (1850, 'sink'),
 (1862, 'hang'),
 (1864, 'wait'),
 (1877, 'sing'),
 (1878, 'return'),
 (1889, 'make'),
 (1902, 'glance'),
 (1909, 'jerk'),
 (1911, 'study'),
 (1912, 'grip'),
 (1914, 'see'),
 (1920, 'bow'),
 (1921, 'feel'),
 (1925, 'gaze'),
 (1926, 'ignore'),
 (1927, 'clasp'),
 (1930, 'mix'),
 (1932, 'work'),
 (1943, 'carry'),
 (1944, 'relish'),
 (1945, 'greeting'),
 (1949, 'study'),
 (1950, 'promise'),
 (1952, 'look'),
 (1954, 'listen'),
 (1958, 'try'),
 (1962, 'choose'),
 (1963, 'expect'),
 (1967, 'glitter'),
 (1971, 'pull'),
 (1972, 'hope'),
 (1976, 'smile'),
 (1978, 'dust'),
 (1981, 'mopp'),
 (1984, 'lean'),
 (1987, 'decide'),
 (1991, 'stabbing'),
 (1993, 'shake'),
 (1995, 'leave'),
 (2001, 'press'),
 (2007, 'capture'),
 (2012, 'stare'),
 (2013, 'move'),
 (2024, 'pick'),
 (2032, 'leave'),
 (2036, 'shake'),
 (2040, 'gaze'),
 (2055, 'look'),
 (2065, 'jerk'),
 (2066, 'wait'),
 (2067, 'fling'),
 (2068, 'hold'),
 (2069, 'push'),
 (2073, 'turn'),
 (2074, 'walk'),
 (2078, 'frown'),
 (2079, 'try'),
 (2082, 'wait'),
 (2083, 'frown'),
 (2089, 'tread'),
 (2090, 'carry'),
 (2092, 'pick'),
 (2100, 'nodd'),
 (2122, 'shake'),
 (2125, 'lead'),
 (2128, 'sit'),
 (2129, 'watch'),
 (2133, 'study'),
 (2139, 'wait'),
 (2144, 'hold'),
 (2146, 'touch'),
 (2147, 'clutch'),
 (2148, 'make'),
 (2165, 'give'),
 (2166, 'promise'),
 (2173, 'seek'),
 (2175, 'jump'),
 (2178, 'glow'),
 (2187, 'turn'),
 (2190, 'twist'),
 (2191, 'make'),
 (2198, 'look'),
 (2206, 'glance'),
 (2209, 'wonder'),
 (2212, 'wedg'),
 (2215, 'sit'),
 (2221, 'make'),
 (2224, 'glance'),
 (2225, 'wink'),
 (2228, 'desert'),
 (2237, 'try'),
 (2244, 'try'),
 (2248, 'cease'),
 (2249, 'run'),
 (2250, 'toss'),
 (2251, 'find'),
 (2257, 'surprising'),
 (2262, 'leave'),
 (2265, 'turn'),
 (2272, 'leave'),
 (2273, 'chat'),
 (2274, 'take'),
 (2278, 'wipe'),
 (2283, 'walk'),
 (2284, 'look'),
 (2286, 'mingle'),
 (2288, 'exchang'),
 (2291, 'lean'),
 (2292, 'wriggle'),
 (2294, 'cut'),
 (2295, 'throw'),
 (2302, 'look'),
 (2306, 'imply'),
 (2309, 'break'),
 (2317, 'except'),
 (2319, 'look'),
 (2329, 'stare'),
 (2333, 'draw'),
 (2336, 'repair'),
 (2339, 'look'),
 (2344, 'lean'),
 (2346, 'advance'),
 (2358, 'stare'),
 (2359, 'take'),
 (2360, 'mutter'),
 (2370, 'tremble'),
 (2379, 'change'),
 (2381, 'stand'),
 (2387, 'know'),
 (2389, 'raise'),
 (2391, 'elude'),
 (2412, 'look'),
 (2414, 'wash'),
 (2421, 'paw'),
 (2423, 'take'),
 (2427, 'make'),
 (2430, 'endow'),
 (2431, 'read'),
 (2436, 'waste'),
 (2438, 'imagin'),
 (2446, 'move'),
 (2456, 'sit'),
 (2469, 'look'),
 (2473, 'pocket'),
 (2479, 'take'),
 (2480, 'tip'),
 (2486, 'talk'),
 (2490, 'look'),
 (2491, 'remember'),
 (2495, 'lean'),
 (2496, 'leave'),
 (2504, 'sit'),
 (2517, 'rub'),
 (2529, 'tighten'),
 (2531, 'turn'),
 (2534, 'look'),
 (2539, 'hope'),
 (2543, 'drag'),
 (2544, 'judge'),
 (2563, 'shake'),
 (2566, 'open'),
 (2570, 'lean'),
 (2571, 'rise'),
 (2576, 'look'),
 (2588, 'take'),
 (2596, 'recover'),
 (2600, 'touch'),
 (2601, 'examine'),
 (2602, 'examine'),
 (2605, 'call'),
 (2606, 'cut'),
 (2613, 'add'),
 (2614, 'decking'),
 (2616, 'leave'),
 (2622, 'suspect'),
 (2624, 'rest'),
 (2632, 'stand'),
 (2633, 'ring'),
 (2634, 'realize'),
 (2637, 'concentrate'),
 (2639, 'disappear'),
 (2650, 'add'),
 (2665, 'bring'),
 (2666, 'follow'),
 (2673, 'nodd'),
 (2679, 'listen'),
 (2681, 'wonder'),
 (2688, 'hold'),
 (2690, 'carry'),
 (2691, 'glisten'),
 (2692, 'indicate'),
 (2697, 'kiss'),
 (2699, 'hold'),
 (2701, 'turn'),
 (2702, 'preced'),
 (2708, 'beat'),
 (2709, 'mould'),
 (2719, 'shuffle'),
 (2721, 'wrap'),
 (2725, 'press'),
 (2726, 'touch'),
 (2727, 'leave'),
 (2728, 'realize'),
 (2732, 'breathe'),
 (2736, 'shade'),
 (2760, 'fix'),
 (2770, 'smile'),
 (2798, 'deny'),
 (2799, 'defend'),
 (2801, 'try'),
 (2802, 'struggle'),
 (2805, 'exult'),
 (2813, 'say'),
 (2820, 'intend'),
 (2822, 'wave'),
 (2832, 'sway'),
 (2841, 'go'),
 (2843, 'sway'),
 (2845, 'watch'),
 (2847, 'shake'),
 (2854, 'avoid'),
 (2857, 'pass'),
 (2862, 'intend'),
 (2869, 'come'),
 (2875, 'cross'),
 (2882, 'watch'),
 (2884, 'cross'),
 (2886, 'throw'),
 (2892, 'pervade'),
 (2894, 'leave'),
 (2896, 'get'),
 (2904, 'summ'),
 (2911, 'fill'),
 (2915, 'promise'),
 (2917, 'walk'),
 (2927, 'conceal'),
 (2933, 'take'),
 (2945, 'try'),
 (2947, 'know'),
 (2948, 'point'),
 (2949, 'hold'),
 (2959, 'stand'),
 (2962, 'nodd'),
 (2968, 'go'),
 (2969, 'inquire'),
 (2976, 'trace'),
 (2990, 'try'),
 (2995, 'hold'),
 (2996, 'remark'),
 (3009, 'read'),
 (3023, 'crouch'),
 (3031, 'move'),
 (3032, 'adapt'),
 (3035, 'hold'),
 (3045, 'draw'),
 (3055, 'look'),
 (3065, 'throw'),
 (3072, 'smoke'),
 (3080, 'shuffle'),
 (3082, 'read'),
 (3093, 'carry'),
 (3102, 'digg'),
 (3105, 'want'),
 (3112, 'sprint'),
 (3124, 'sniff'),
 (3131, 'say'),
 (3136, 'leave'),
 (3140, 'read'),
 (3154, 'go'),
 (3155, 'try'),
 (3161, 'take'),
 (3162, 'spend'),
 (3176, 'wear'),
 (3182, 'watch'),
 (3183, 'whoopee'),
 (3189, 'say'),
 (3194, 'hitch'),
 (3199, 'hear'),
 (3211, 'wait'),
 (3212, 'dawdle'),
 (3239, 'call'),
 (3248, 'stoke'),
 (3253, 'look'),
 (3254, 'come'),
 (3273, 'wear'),
 (3284, 'look'),
 (3332, 'hold'),
 (3336, 'water'),
 (3343, 'ruing'),
 (3347, 'look'),
 (3349, 'glory'),
 (3360, 'thread'),
 (3362, 'stare'),
 (3377, 'look'),
 (3381, 'save'),
 (3384, 'fool'),
 (3402, 'work'),
 (3405, 'talk'),
 (3406, 'ask'),
 (3412, 'agree'),
 (3417, 'gun'),
 (3419, 'drive'),
 (3420, 'make'),
 (3423, 'symbolize'),
 (3431, 'compose'),
 (3432, 'wear'),
 (3434, 'suck'),
 (3435, 'hitch'),
 (3447, 'get'),
 (3450, 'face'),
 (3454, 'give'),
 (3458, 'run'),
 (3461, 'talk'),
 (3474, 'punch'),
 (3476, 'revert'),
 (3479, 'come'),
 (3488, 'figure'),
 (3489, 'hurry'),
 (3503, 'bring'),
 (3518, 'turn'),
 (3535, 'turn'),
 (3536, 'clutch'),
 (3537, 'imitate'),
 (3539, 'escort'),
 (3540, 'bow'),
 (3542, 'rise'),
 (3557, 'rise'),
 (3588, 'look'),
 (3593, 'talk'),
 (3602, 'spend'),
 (3603, 'meet'),
 (3605, 'arrive'),
 (3618, 'wait'),
 (3619, 'save'),
 (3620, 'smile'),
 (3621, 'laugh'),
 (3622, 'choke'),
 (3623, 'lean'),
 (3624, 'raise'),
 (3636, 'write'),
 (3642, 'buy'),
 (3644, 'fall'),
 (3645, 'wait'),
 (3647, 'know'),
 (3648, 'shift'),
 (3653, 'read'),
 (3659, 'bother'),
 (3668, 'reminisce'),
 (3677, 'reach'),
 (3687, 'try'),
 (3691, 'look'),
 (3699, 'devise'),
 (3702, 'realize'),
 (3704, 'hope'),
 (3731, 'take'),
 (3767, 'plan'),
 (3768, 'carry'),
 (3775, 'wait'),
 (3779, 'switch'),
 (3804, 'close'),
 (3813, 'suspicion'),
 (3814, 'think'),
 (3819, 'take'),
 (3820, 'hurry'),
 (3821, 'fix'),
 (3830, 'float'),
 (3834, 'try'),
 (3836, 'look'),
 (3837, 'wet'),
 (3840, 'argue'),
 (3843, 'finger'),
 (3853, 'sing'),
 (3854, 'sing'),
 (3857, 'holding'),
 (3858, 'thumb'),
 (3860, 'see'),
 (3869, 'ride'),
 (3873, 'ask'),
 (3904, 'digg'),
 (3929, 'sigh'),
 (3937, 'curse'),
 (3938, 'sopp'),
 (3939, 'call'),
 (3953, 'talk'),
 (3955, 'put'),
 (3963, 'digg'),
 (3965, 'slamm'),
 (3975, 'carry'),
 (3976, 'eat'),
 (3979, 'hope'),
 (3991, 'commanding'),
 (3992, 'hit'),
 (4011, 'wait'),
 (4019, 'try'),
 (4022, 'wait'),
 (4024, 'cross'),
 (4031, 'tell'),
 (4034, 'make'),
 (4049, 'dropp'),
 (4054, 'look'),
 (4058, 'listen'),
 (4061, 'roll'),
 (4062, 'rub'),
 (4071, 'trail'),
 (4076, 'poke'),
 (4079, 'look'),
 (4094, 'talk'),
 (4095, 'talk'),
 (4098, 'flutter'),
 (4102, 'stand'),
 (4103, 'finger'),
 (4106, 'promise'),
 (4112, 'kiss'),
 (4129, 'wake'),
 (4132, 'bustle'),
 (4133, 'call'),
 (4136, 'watch'),
 (4137, 'wear'),
 (4142, 'take'),
 (4145, 'cross'),
 (4146, 'pull'),
 (4147, 'clasp'),
 (4150, 'assert'),
 (4151, 'steal'),
 (4155, 'demonstrate'),
 (4156, 'go'),
 (4158, 'go'),
 (4164, 'try'),
 (4170, 'tell'),
 (4173, 'nodd'),
 (4176, 'ponder'),
 (4178, 'follow'),
 (4183, 'swerve'),
 (4186, 'try'),
 (4187, 'face'),
 (4189, 'wear'),
 (4206, 'digg'),
 (4218, 'shouting'),
 (4219, 'repeat'),
 (4223, 'snapp'),
 (4226, 'drip'),
 (4232, 'know'),
 (4242, 'sit'),
 (4247, 'put'),
 (4249, 'mumble'),
 (4251, 'nodd'),
 (4255, 'look'),
 (4259, 'interview'),
 (4262, 'know'),
 (4263, 'listen'),
 (4278, 'expire'),
 (4279, 'drop'),
 (4285, 'hide'),
 (4289, 'yell'),
 (4308, 'go'),
 (4314, 'expect'),
 (4323, 'knock'),
 (4329, 'poke'),
 (4332, 'wait'),
 (4346, 'Roll'),
 (4355, 'smile'),
 (4357, 'talk'),
 (4359, 'fly'),
 (4367, 'point'),
 (4369, 'bustle'),
 (4374, 'stoke'),
 (4375, 'hopping'),
 (4380, 'pass'),
 (4385, 'smile'),
 (4394, 'gobble'),
 (4396, 'wear'),
 (4401, 'survey'),
 (4402, 'watch'),
 (4403, 'look'),
 (4404, 'slip'),
 (4406, 'scream'),
 (4415, 'wait'),
 (4416, 'talk'),
 (4421, 'put'),
 (4427, 'see'),
 (4430, 'snuff'),
 (4439, 'snuff'),
 (4441, 'take'),
 (4442, 'clutch'),
 (4465, 'put'),
 (4468, 'yell'),
 (4471, 'lean'),
 (4472, 'pick'),
 (4481, 'sleep'),
 (4492, 'stand'),
 (4493, 'hold'),
 (4500, 'yell'),
 (4508, 'wave'),
 (4514, 'smile'),
 (4541, 'try'),
 (4543, 'try'),
 (4551, 'droop'),
 (4563, 'look'),
 (4565, 'watch'),
 (4568, 'arrive'),
 (4575, 'hoot'),
 (4579, 'weep'),
 (4581, 'take'),
 (4593, 'turn'),
 (4594, 'laugh'),
 (4602, 'rub'),
 (4606, 'pay'),
 (4613, 'look'),
 (4614, 'write'),
 (4617, 'tip'),
 (4622, 'make'),
 (4626, 'drink'),
 (4627, 'drink'),
 (4628, 'try'),
 (4633, 'give'),
 (4634, 'pound'),
 (4643, 'carry'),
 (4646, 'look'),
 (4653, 'pick'),
 (4658, 'forget'),
 (4668, 'vie'),
 (4677, 'demonstrate'),
 (4678, 'look'),
 (4685, 'tap'),
 (4686, 'make'),
 (4688, 'get'),
 (4689, 'say'),
 (4694, 'look'),
 (4701, 'listen'),
 (4704, 'hit'),
 (4707, 'think'),
 (4710, 'sneez'),
 (4712, 'wish'),
 (4713, 'feel'),
 (4714, 'stroll'),
 (4716, 'blush'),
 (4718, 'wish'),
 (4720, 'perform'),
 (4722, 'talk'),
 (4731, 'say'),
 (4743, 'stare'),
 (4751, 'say'),
 (4752, 'visit'),
 (4759, 'cure'),
 (4775, 'chat'),
 (4779, 'throw'),
 (4780, 'say'),
 (4785, 'adjust'),
 (4799, 'look'),
 (4804, 'work'),
 (4808, 'read'),
 (4814, 'look'),
 (4816, 'ply'),
 (4820, 'break'),
 (4823, 'leave'),
 (4824, 'look'),
 (4830, 'goof'),
 (4835, 'tell'),
 (4842, 'say'),
 (4846, 'defend'),
 (4852, 'digg'),
 (4858, 'hear'),
 (4860, 'go'),
 (4864, 'yell'),
 (4866, 'blow'),
 (4878, 'loop'),
 (4883, 'shake'),
 (4885, 'fall'),
 (4890, 'make'),
 (4893, 'shudder'),
 (4895, 'blow'),
 (4898, 'clap'),
 (4906, 'fall'),
 (4909, 'giggle'),
 (4914, 'light'),
 (4921, 'wear'),
 (4925, 'sway'),
 (4934, 'yell'),
 (4935, 'fall'),
 (4939, 'scream'),
 (4947, 'sock'),
 (4955, 'hang'),
 (4960, 'carry'),
 (4962, 'look'),
 (4964, 'spinn'),
 (4965, 'spinn'),
 ...]

# Parse Romanian

In [ ]:
process_ro = multiprocessing.Process(
    target=functions_stanza.parse_in_chunks, args=(df, "ro", 7, "ingforms", CHUNK_SIZE)
)

In [ ]:
process_ro.start()

2026-03-03 14:20:16 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json: 439kB [00:00, 21.9MB/s]
2026-03-03 14:20:16 INFO: Downloaded file to /home/christopher/stanza_resources/resources.json
2026-03-03 14:20:18 INFO: Loading these models for language: en (English):
============================================
| Processor    | Package                   |
--------------------------------------------
| tokenize     | combined                  |
| mwt          | combined                  |
| pos          | combined_charlm           |
| lemma        | combined_nocharlm         |
| constituency | ptb3-revised_charlm       |
| depparse     | combined_charlm           |
| sentiment    | sstplus_charlm            |
| ner          | ontonotes-ww-multi_charlm |
============================================

2026-03-03 14:20:18 INFO: Using device: cpu
2026-03-03 14:20:18 INFO: Loading: tokenize
2026-03-03 14:20:20 INFO: Loading: mwt
2026-03-03 14:20:20 INFO: Loading: pos
2026-03-03 14:20:22 INFO: Loading: lemma
2026-03-03 14:20:23 INFO: Loading: constituency
2026-03-03 14:20:25 INFO: Loading: depparse
2026-03-03 14:20:25 INFO: Loading: sentiment
2026-03-03 14:20:26 INFO: Loading: ner
2026-03-03 14:20:28 INFO: Done loading processors!
2026-03-03 14:20:28 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json: 439kB [00:00, 21.7MB/s]
2026-03-03 14:20:28 INFO: Downloaded file to /home/christopher/stanza_resources/resources.json
2026-03-03 14:20:29 INFO: Loading these models for language: ro (Romanian):
============================
| Processor | Package      |
----------------------------
| tokenize  | rrt          |
| pos       | rrt_nocharlm |
| lemma     | rrt_nocharlm |
| depparse  | rrt_nocharlm |
============================

2026-03-03 14:20:29 INFO: Using device: cpu
2026-03-03 14:20:29 INFO: Loading: tokenize
2026-03-03 14:20:29 INFO: Loading: pos
2026-03-03 14:20:31 INFO: Loading: lemma
2026-03-03 14:20:32 INFO: Loading: depparse
2026-03-03 14:20:33 INFO: Done loading processors!

Parsing chunk 0 to 2499
Parsing chunk 2500 to 4999
Parsing chunk 5000 to 7499
Parsing chunk 7500 to 9999
Parsing chunk 2500 to 4999
Parsing chunk 10000 to 12499
Parsing chunk 12500 to 14999
Parsing chunk 15000 to 17499
Parsing chunk 17500 to 19999
Parsing chunk 5000 to 7499
Parsing chunk 20000 to 22499
Parsing chunk 22500 to 24999
Parsing chunk 25000 to 27499
Parsing chunk 27500 to 29414
Parsing chunk 7500 to 9999
Parsing chunk 10000 to 12499
Parsing chunk 12500 to 14999
Parsing chunk 15000 to 17499
Parsing chunk 17500 to 19999
Parsing chunk 20000 to 22499

In [17]:
parsed_dict_ro = functions_stanza.load_pickled_data(folder="ingforms", language="ro")

parsed_slice_en_27500_29414.pkl
parsed_slice_en_17500_19999.pkl
parsed_slice_ro_20000_22499.pkl
parsed_slice_en_7500_9999.pkl
parsed_slice_ro_17500_19999.pkl
parsed_slice_ro_10000_12499.pkl
parsed_slice_en_20000_22499.pkl
parsed_slice_ro_0_2499.pkl
parsed_slice_ro_15000_17499.pkl
parsed_slice_en_12500_14999.pkl
parsed_slice_en_2500_4999.pkl
parsed_slice_ro_5000_7499.pkl
parsed_slice_ro_25000_27499.pkl
parsed_slice_en_10000_12499.pkl
parsed_slice_en_25000_27499.pkl
parsed_slice_ro_22500_24999.pkl
parsed_slice_ro_12500_14999.pkl
parsed_slice_en_0_2499.pkl
parsed_slice_ro_27500_29414.pkl
parsed_slice_ro_7500_9999.pkl
parsed_slice_en_22500_24999.pkl
parsed_slice_ro_2500_4999.pkl
parsed_slice_en_15000_17499.pkl
parsed_slice_en_5000_7499.pkl

In [18]:
gerunziu_indices_and_words = []

In [19]:
for i in range(0, len(df)):
    gerunzius = functions_stanza.get_gerunzius_in_sentences(parsed_dict_ro[i])
    if gerunzius:
        gerunziu_indices_and_words.append((i, gerunzius))

In [20]:
gerunziu_indices_and_words

[(8, [('Văzând', 'vedea')]),
 (10, [('alunecând', 'aluneca')]),
 (11, [('alunecând', 'aluneca')]),
 (17, [('fiind', 'fi')]),
 (24, [('plimbându', 'plimba'), ('întrebând', 'întreba')]),
 (25, [('plimbându', 'plimba'), ('întrebând', 'întreba')]),
 (26, [('plimbându', 'plimba'), ('întrebând', 'întreba')]),
 (27, [('alergând', 'alerga')]),
 (28, [('bombănind', 'bombăni')]),
 (30, [('încercând', 'încerca'), ('întrebându', 'întrebându')]),
 (31, [('încercând', 'încerca'), ('întrebându', 'întrebându')]),
 (32, [('trăgând', 'trage')]),
 (33, [('trăgând', 'trage')]),
 (34, [('trăgând', 'trage')]),
 (36, [('găsind', 'găsi')]),
 (50, [('întrebându', 'întrebându'), ('ţinându', 'ţina')]),
 (51, [('întrebându', 'întrebându'), ('ţinându', 'ţina')]),
 (52, [('întrebându', 'întrebându'), ('ţinându', 'ţina')]),
 (63, [('ţinând', 'ţinca'), ('bombănind', 'bombăni')]),
 (64, [('ţinând', 'ţinca'), ('bombănind', 'bombăni')]),
 (65, [('ţinând', 'ţinca'), ('bombănind', 'bombăni')]),
 (67, [('spunându', 'spune')]),
 (68, [('spunându', 'spune')]),
 (70, [('încercând', 'încerca')]),
 (75, [('spunând', 'spune')]),
 (83, [('înotând', 'înota'), ('sirăduindu', 'sirădui')]),
 (84, [('plescăind', 'plescăi'), ('amintindu', 'aminti')]),
 (88, [('continuând', 'continua')]),
 (89, [('continuând', 'continua')]),
 (90, [('continuând', 'continua')]),
 (91, [('continuând', 'continua')]),
 (92, [('continuând', 'continua')]),
 (94, [('stârnind', 'stârni')]),
 (95, [('stârnind', 'stârni')]),
 (96, [('tremurând', 'tremura')]),
 (98, [('şiroind', 'şiroi'), ('simţindu', 'simţi')]),
 (99, [('şiroind', 'şiroi'), ('simţindu', 'simţi')]),
 (100, [('şiroind', 'şiroi'), ('simţindu', 'simţi')]),
 (103, [('în-cruntându', 'în-crunta')]),
 (104, [('întorcându', 'întoarce')]),
 (105, [('întorcându', 'întoarce')]),
 (106, [('ridicându', 'ridica')]),
 (108, [('-du', 'duce')]),
 (109, [('gâfâind', 'gâfâi'), ('întrebând', 'întreba')]),
 (110, [('gâfâind', 'gâfâi'), ('întrebând', 'întreba')]),
 (111, [('gâfâind', 'gâfâi'), ('întrebând', 'întreba')]),
 (112, [('arătând', 'arăta')]),
 (113, [('strigând', 'striga')]),
 (114, [('întorcându', 'întoarce')]),
 (115, [('spunând', 'spune')]),
 (116, [('luându', 'lua')]),
 (117, [('întorcându', 'întoarce'), ('oftând', 'ofta')]),
 (118, [('întorcându', 'întoarce'), ('oftând', 'ofta')]),
 (119, [('măsurând', 'măsura')]),
 (123, [('uitându', 'uita')]),
 (124, [('ridicându', 'ridica'), ('îndepărtându', 'îndepărta')]),
 (125, [('ridicându', 'ridica'), ('îndepărtându', 'îndepărta')]),
 (126, [('îndrugând', 'îndruge')]),
 (127, [('suspinând', 'suspine')]),
 (130, [('zicând', 'zice'), ('zicându', 'zice')]),
 (131, [('zicând', 'zice'), ('zicându', 'zice')]),
 (132, [('zicând', 'zice'), ('zicându', 'zice')]),
 (133, [('zicând', 'zice'), ('zicându', 'zice')]),
 (134, [('crezând', 'crede')]),
 (135, [('crezând', 'crede')]),
 (136, [('aruncând', 'arunca')]),
 (137, [('aruncând', 'arunca')]),
 (138, [('bombănind', 'bombăni')]),
 (144, [('temându', 'temandu')]),
 (149, [('punând', 'pune')]),
 (153, [('spunându', 'spune')]),
 (154, [('spunându', 'spune')]),
 (155, [('spunându', 'spune')]),
 (156, [('spunându', 'spune')]),
 (159, [('gândind', 'gândi'), ('privind', 'privind'), ('purtând', 'purta')]),
 (160, [('gândind', 'gândi'), ('privind', 'privind'), ('purtând', 'purta')]),
 (161, [('uitând', 'uita')]),
 (162, [('uitând', 'uita')]),
 (171, [('căţărându', 'căţărî')]),
 (172, [('căţărându', 'căţărî')]),
 (173, [('căţărându', 'căţărî')]),
 (176, [('lovindu', 'lovi')]),
 (181, [('făcând', 'face')]),
 (182, [('întinzându', 'întinde')]),
 (183, [('întinzându', 'întinde')]),
 (184, [('întinzându', 'întinde')]),
 (185, [('străduindu', 'strădui')]),
 (186, [('luând', 'lua')]),
 (187, [('aşteptându', 'aştepta')]),
 (188, [('aşteptându', 'aştepta')]),
 (189, [('aşteptându', 'aştepta')]),
 (190,
  [('crezând', 'crede'),
   ('făcând', 'face'),
   ('scoţând', 'scoate'),
   ('gâfâind', 'gâfâi'),
   ('ţinându', 'ţina')]),
 (191,
  [('crezând', 'crede'),
   ('făcând', 'face'),
   ('scoţând', 'scoate'),
   ('gâfâind', 'gâfâi'),
   ('ţinându', 'ţina')]),
 (192,
  [('crezând', 'crede'),
   ('făcând', 'face'),
   ('scoţând', 'scoate'),
   ('gâfâind', 'gâfâi'),
   ('ţinându', 'ţina')]),
 (193,
  [('crezând', 'crede'),
   ('făcând', 'face'),
   ('scoţând', 'scoate'),
   ('gâfâind', 'gâfâi'),
   ('ţinându', 'ţina')]),
 (201, [('stăpânindu', 'stăpâni')]),
 (207, [('înălţându', 'înălţa')]),
 (208, [('du-cându', 'du-ca')]),
 (209, [('rostind', 'rosti')]),
 (210, [('privind', 'privind'), ('încercând', 'încerca')]),
 (211, [('privind', 'privind'), ('încercând', 'încerca')]),
 (214, [('realizând', 'realiza'), ('dorind', 'dori'), ('bătând', 'bate')]),
 (215, [('realizând', 'realiza'), ('dorind', 'dori'), ('bătând', 'bate')]),
 (216, [('realizând', 'realiza'), ('dorind', 'dori'), ('bătând', 'bate')]),
 (217, [('realizând', 'realiza'), ('dorind', 'dori'), ('bătând', 'bate')]),
 (218, [('realizând', 'realiza'), ('dorind', 'dori'), ('bătând', 'bate')]),
 (220, [('luând', 'lua')]),
 (223, [('începând', 'începe')]),
 (224, [('strigând', 'striga')]),
 (225, [('strigând', 'striga')]),
 (226, [('strigând', 'striga')]),
 (241,
  [('între-bându', 'între-ba'),
   ('alergând', 'alerga'),
   ('judecând', 'judeca')]),
 (242,
  [('între-bându', 'între-ba'),
   ('alergând', 'alerga'),
   ('judecând', 'judeca')]),
 (243,
  [('între-bându', 'între-ba'),
   ('alergând', 'alerga'),
   ('judecând', 'judeca')]),
 (244,
  [('între-bându', 'între-ba'),
   ('alergând', 'alerga'),
   ('judecând', 'judeca')]),
 (245, [('spunând', 'spune')]),
 (246, [('spunând', 'spune')]),
 (247, [('schimbând', 'schimba')]),
 (248, [('Văzând', 'vedea')]),
 (249, [('stând', 'sta')]),
 (250, [('stând', 'sta')]),
 (254, [('neţinând', 'neţina')]),
 (259, [('începând', 'începe')]),
 (261, [('ţinând', 'ţinca')]),
 (262, [('ţinând', 'ţinca')]),
 (263, [('ţinând', 'ţinca')]),
 (264, [('ţinând', 'ţinca')]),
 (268, [('rânjind', 'rânji')]),
 (269, [('rânjind', 'rânji')]),
 (280, [('cântându', 'cânta'), ('scuturându', 'scutura')]),
 (281, [('cântându', 'cânta'), ('scuturându', 'scutura')]),
 (282, [('cântându', 'cânta'), ('scuturându', 'scutura')]),
 (284, [('zvârlind', 'zvârli')]),
 (292, [('privindu', 'privi')]),
 (295, [('întrebându', 'întrebându')]),
 (296, [('întrebându', 'întrebându')]),
 (297, [('întrebându', 'întrebându')]),
 (298, [('întrebându', 'întrebându')]),
 (299, [('arătând', 'arăta'), ('fluturându', 'flutura')]),
 (300, [('arătând', 'arăta'), ('fluturându', 'flutura')]),
 (306, [('aşteptându', 'aştepta')]),
 (311,
  [('dispărând', 'dispărea'), ('începând', 'începe'), ('sfârşind', 'sfârşi')]),
 (312,
  [('dispărând', 'dispărea'), ('începând', 'începe'), ('sfârşind', 'sfârşi')]),
 (313, [('spunându', 'spune')]),
 (314, [('spunându', 'spune')]),
 (315, [('sprijinindu', 'sprijini'), ('vorbind', 'vorbi')]),
 (316, [('sprijinindu', 'sprijini'), ('vorbind', 'vorbi')]),
 (317, [('sprijinindu', 'sprijini'), ('vorbind', 'vorbi')]),
 (318, [('sprijinindu', 'sprijini'), ('vorbind', 'vorbi')]),
 (319, [('sprijinindu', 'sprijini'), ('vorbind', 'vorbi')]),
 (320, [('apropiindu', 'apropii')]),
 (323, [('mulţumindu', 'mulţumi')]),
 (326,
  [('întorcându', 'întoarce'),
   ('scuturându', 'scutura'),
   ('ducându', 'duce')]),
 (327,
  [('întorcându', 'întoarce'),
   ('scuturându', 'scutura'),
   ('ducându', 'duce')]),
 (328,
  [('întorcându', 'întoarce'),
   ('scuturându', 'scutura'),
   ('ducându', 'duce')]),
 (329,
  [('întorcându', 'întoarce'),
   ('scuturându', 'scutura'),
   ('ducându', 'duce')]),
 (330, [('săgetându', 'săgeta')]),
 (334, [('întorcându', 'întoarce')]),
 (337, [('clătinând', 'clătina')]),
 (344, [('căscând', 'căsca')]),
 (354, [('uitându', 'uita')]),
 (358, [('căscând', 'căsca'), ('ştergându', 'şterge')]),
 (359, [('căscând', 'căsca'), ('ştergându', 'şterge')]),
 (360, [('căscând', 'căsca'), ('ştergându', 'şterge')]),
 (361, [('căscând', 'căsca'), ('ştergându', 'şterge')]),
 (363, [('nădăjduind', 'nădăjdui')]),
 (364, [('nădăjduind', 'nădăjdui')]),
 (365, [('nădăjduind', 'nădăjdui')]),
 (366, [('vorbind', 'vorbi')]),
 (372, [('spunând', 'spune')]),
 (378, [('purtând', 'purta')]),
 (379, [('ţinându', 'ţina')]),
 (383, [('purtând', 'purta')]),
 (384, [('dând', 'da')]),
 (386, [('arătând', 'arăta')]),
 (387, [('arătând', 'arăta')]),
 (388, [('având', 'avea')]),
 (391, [('îndreptându', 'îndrepta')]),
 (392, [('îndreptându', 'îndrepta')]),
 (393, [('punând', 'pune')]),
 (394, [('punând', 'pune')]),
 (396, [('rămânând', 'rămâne'), ('nădăjduind', 'nădăjdui')]),
 (397, [('-du', 'duce')]),
 (401, [('împiedicându', 'împiedica')]),
 (402, [('împiedicându', 'împiedica')]),
 (403,
  [('atârnându', 'atârna'),
   ('neaşteptând', 'peaştepta'),
   ('-du', 'duce'),
   ('Văzând', 'vedea'),
   ('urlând', 'urla')]),
 (404,
  [('atârnându', 'atârna'),
   ('neaşteptând', 'peaştepta'),
   ('-du', 'duce'),
   ('Văzând', 'vedea'),
   ('urlând', 'urla')]),
 (405,
  [('atârnându', 'atârna'),
   ('neaşteptând', 'peaştepta'),
   ('-du', 'duce'),
   ('Văzând', 'vedea'),
   ('urlând', 'urla')]),
 (406,
  [('atârnându', 'atârna'),
   ('neaşteptând', 'peaştepta'),
   ('-du', 'duce'),
   ('Văzând', 'vedea'),
   ('urlând', 'urla')]),
 (407,
  [('atârnându', 'atârna'),
   ('neaşteptând', 'peaştepta'),
   ('-du', 'duce'),
   ('Văzând', 'vedea'),
   ('urlând', 'urla')]),
 (408,
  [('atârnându', 'atârna'),
   ('neaşteptând', 'peaştepta'),
   ('-du', 'duce'),
   ('Văzând', 'vedea'),
   ('urlând', 'urla')]),
 (409,
  [('atârnându', 'atârna'),
   ('neaşteptând', 'peaştepta'),
   ('-du', 'duce'),
   ('Văzând', 'vedea'),
   ('urlând', 'urla')]),
 (410,
  [('atârnându', 'atârna'),
   ('neaşteptând', 'peaştepta'),
   ('-du', 'duce'),
   ('Văzând', 'vedea'),
   ('urlând', 'urla')]),
 (411,
  [('atârnându', 'atârna'),
   ('neaşteptând', 'peaştepta'),
   ('-du', 'duce'),
   ('Văzând', 'vedea'),
   ('urlând', 'urla')]),
 (412,
  [('atârnându', 'atârna'),
   ('neaşteptând', 'peaştepta'),
   ('-du', 'duce'),
   ('Văzând', 'vedea'),
   ('urlând', 'urla')]),
 (413,
  [('atârnându', 'atârna'),
   ('neaşteptând', 'peaştepta'),
   ('-du', 'duce'),
   ('Văzând', 'vedea'),
   ('urlând', 'urla')]),
 (414,
  [('atârnându', 'atârna'),
   ('neaşteptând', 'peaştepta'),
   ('-du', 'duce'),
   ('Văzând', 'vedea'),
   ('urlând', 'urla')]),
 (415,
  [('atârnându', 'atârna'),
   ('neaşteptând', 'peaştepta'),
   ('-du', 'duce'),
   ('Văzând', 'vedea'),
   ('urlând', 'urla')]),
 (416,
  [('atârnându', 'atârna'),
   ('neaşteptând', 'peaştepta'),
   ('-du', 'duce'),
   ('Văzând', 'vedea'),
   ('urlând', 'urla')]),
 (417,
  [('atârnându', 'atârna'),
   ('neaşteptând', 'peaştepta'),
   ('-du', 'duce'),
   ('Văzând', 'vedea'),
   ('urlând', 'urla')]),
 (425, [('vorbind', 'vorbi')]),
 (426, [('venind', 'veni')]),
 (427, [('venind', 'veni')]),
 (430, [('apropiindu', 'apropii'), ('uitându', 'uita')]),
 (431, [('apropiindu', 'apropii'), ('uitându', 'uita')]),
 (432, [('apropiindu', 'apropii'), ('uitându', 'uita')]),
 (436, [('strigând', 'striga')]),
 (437, [('strigând', 'striga')]),
 (438, [('bătându', 'bate')]),
 (439, [('bătându', 'bate')]),
 (450, [('lovind', 'lovi')]),
 (455, [('lovindu', 'lovi')]),
 (457, [('stând', 'sta')]),
 (458, [('bătând', 'bate')]),
 (459, [('profitând', 'profita'), ('făcând', 'face')]),
 (460, [('profitând', 'profita'), ('făcând', 'face')]),
 (461, [('răcnind', 'răcni')]),
 (462, [('răcnind', 'răcni')]),
 (463, [('răcnind', 'răcni')]),
 (465, [('lăsând', 'lăsa')]),
 (466, [('suspinând', 'suspine')]),
 (467, [('suspinând', 'suspine')]),
 (468, [('vrând', 'vrea')]),
 (469, [('vrând', 'vrea')]),
 (470, [('vrând', 'vrea')]),
 (472, [('fiindu', 'fi'), ('privind', 'privind')]),
 (478, [('numărând', 'număra')]),
 (479, [('numărând', 'număra')]),
 (480, [('numărând', 'număra')]),
 (481, [('numărând', 'număra')]),
 (482, [('oftând', 'ofta')]),
 (483, [('începând', 'începe')]),
 (484, [('începând', 'începe')]),
 (485, [('şiroindu', 'şiroi')]),
 (486, [('făcând', 'face')]),
 (487, [('coborându', 'coborî')]),
 (488, [('uitându', 'uita')]),
 (491, [('călcând', 'călca'), ('bătând', 'bate')]),
 (492, [('călcând', 'călca'), ('bătând', 'bate')]),
 (493, [('călcând', 'călca'), ('bătând', 'bate')]),
 (498, [('începând', 'începe')]),
 (499, [('începând', 'începe')]),
 (504, [('întrebându', 'întrebându')]),
 (510, [('trăgând', 'trage')]),
 (511, [('trăgând', 'trage')]),
 (512, [('păzindu', 'păzi')]),
 (524, [('întorcându', 'întoarce')]),
 (526, [('lăsându', 'lăsa'), ('uitându', 'uita')]),
 (527, [('lăsându', 'lăsa'), ('uitându', 'uita')]),
 (533, [('Auzind', 'auzi')]),
 (542, [('Fiind', 'fi')]),
 (543, [('căutând', 'căuta')]),
 (544, [('amintindu', 'aminti')]),
 (545, [('amintindu', 'aminti')]),
 (546, [('amintindu', 'aminti')]),
 (547, [('amintindu', 'aminti')]),
 (550, [('privind', 'privind')]),
 (551, [('fiindu', 'fi')]),
 (552, [('privind', 'privind')]),
 (553, [('-du', 'duce')]),
 (555, [('încrun-tându', 'încrun-ta'), ('schimonosindu', 'schimonosi')]),
 (556, [('încrun-tându', 'încrun-ta'), ('schimonosindu', 'schimonosi')]),
 (561, [('frecându', 'freca')]),
 (563, [('punând', 'pune'), ('uitându', 'uita'), ('-du', 'duce')]),
 (564, [('punând', 'pune'), ('uitându', 'uita'), ('-du', 'duce')]),
 (565, [('punând', 'pune'), ('uitându', 'uita'), ('-du', 'duce')]),
 (567, [('arătând', 'arăta')]),
 (568, [('aruncând', 'arunca')]),
 (570, [('folosind', 'folosi')]),
 (571, [('folosind', 'folosi')]),
 (572, [('aruncând', 'arunca')]),
 (574, [('învineţindu', 'învineţi')]),
 (575, [('dând', 'da')]),
 (576, [('dând', 'da')]),
 (577, [('dând', 'da')]),
 (580, [('alergând', 'alerga')]),
 (581, [('privind', 'privind'), ('gândindu', 'gândi')]),
 (582, [('privind', 'privind'), ('gândindu', 'gândi')]),
 (583, [('privind', 'privind'), ('gândindu', 'gândi')]),
 (584, [('privind', 'privind'), ('gândindu', 'gândi')]),
 (585, [('privind', 'privind'), ('gândindu', 'gândi')]),
 (586, [('cuprinzându', 'cuprinde'), ('făcând', 'face')]),
 (587, [('cuprinzându', 'cuprinde'), ('făcând', 'face')]),
 (588,
  [('stârnind', 'stârni'),
   ('poruncind', 'porunci'),
   ('amestecându', 'amesteca')]),
 (589,
  [('stârnind', 'stârni'),
   ('poruncind', 'porunci'),
   ('amestecându', 'amesteca')]),
 (590,
  [('stârnind', 'stârni'),
   ('poruncind', 'porunci'),
   ('amestecându', 'amesteca')]),
 (591,
  [('stârnind', 'stârni'),
   ('poruncind', 'porunci'),
   ('amestecându', 'amesteca')]),
 (596,
  [('păstrându', 'păstra'),
   ('adunând', 'aduna'),
   ('întristându', 'întrista'),
   ('înveselindu', 'înveseli')]),
 (610, [('străduindu', 'strădui')]),
 (616, [('studiind', 'studia')]),
 (617, [('arătând', 'arăta')]),
 (627, [('arzându', 'arde')]),
 (628, [('arzându', 'arde')]),
 (629, [('arzându', 'arde')]),
 (630, [('arzându', 'arde')]),
 (631, [('luându', 'lua')]),
 (637, [('gândindu', 'gândi'), ('ştiind', 'şti')]),
 (638, [('gândindu', 'gândi'), ('ştiind', 'şti')]),
 (639, [('gândindu', 'gândi'), ('ştiind', 'şti')]),
 (640, [('gândindu', 'gândi'), ('ştiind', 'şti')]),
 (645, [('târşindu', 'târşi'), ('pipăindu', 'pipăi')]),
 (648, [('acoperindu', 'acoperi')]),
 (649, [('acoperindu', 'acoperi')]),
 (650, [('fierbând', 'fierbe')]),
 (651, [('ducându', 'duce')]),
 (663, [('căutând', 'căuta')]),
 (665, [('traversând', 'traversa')]),
 (666, [('despărţind', 'despărţi')]),
 (675, [('spărgându', 'spărge')]),
 (676, [('lăsându', 'lăsa')]),
 (680, [('blocând', 'bloca')]),
 (681, [('blocând', 'bloca')]),
 (682, [('privind', 'privind')]),
 (683, [('ţinându', 'ţina')]),
 (697, [('gândindu', 'gândi')]),
 (714, [('şter-gându', 'şter-ge')]),
 (715, [('întinzând', 'întinde')]),
 (722, [('plutind', 'pluti')]),
 (723, [('întorcându', 'întoarce')]),
 (724, [('sperând', 'spera')]),
 (725, [('sperând', 'spera')]),
 (774, [('călcând', 'călca')]),
 (775, [('călcând', 'călca')]),
 (776, [('călcând', 'călca')]),
 (782, [('coborând', 'coborî')]),
 (794, [('urcând', 'urca'), ('apucându', 'apuca'), ('tragându', 'trage')]),
 (795, [('urcând', 'urca'), ('apucându', 'apuca'), ('tragându', 'trage')]),
 (797, [('strecurându', 'strecura')]),
 (802, [('Uitându', 'uita')]),
 (803, [('Uitându', 'uita')]),
 (806, [('atingând', 'atinge')]),
 (812, [('rânduind', 'rândui')]),
 (815, [('încercând', 'încerca')]),
 (818, [('ţinând', 'ţinca')]),
 (819, [('ţinând', 'ţinca')]),
 (820, [('ţinând', 'ţinca')]),
 (821, [('ţinând', 'ţinca')]),
 (827, [('stu-diindu', 'stu-dia')]),
 (835, [('turnând', 'turna')]),
 (851, [('uitându', 'uita')]),
 (880, [('aşteptând', 'aştepta')]),
 (887, [('luând', 'lua')]),
 (889, [('gândindu', 'gândi')]),
 (895, [('împărţind', 'împărţi')]),
 (896, [('împărţind', 'împărţi')]),
 (898, [('sărind', 'sări'), ('apucându', 'apuca')]),
 (899, [('sărind', 'sări'), ('apucându', 'apuca')]),
 (900, [('apucându', 'apuca')]),
 (902, [('ţinându', 'ţina')]),
 (903, [('încercând', 'încerca')]),
 (918, [('privindu', 'privi')]),
 (919, [('privindu', 'privi')]),
 (920, [('privindu', 'privi')]),
 (921, [('uitându', 'uita')]),
 (924, [('însufleţindu', 'însufleţi')]),
 (925, [('însufleţindu', 'însufleţi')]),
 (926, [('tocând', 'toca')]),
 (938, [('ciupindu', 'ciupi')]),
 (956, [('rotindu', 'roti')]),
 (957, [('rotindu', 'roti')]),
 (958, [('rotindu', 'roti')]),
 (969, [('ţinând', 'ţinca')]),
 (971, [('chicotind', 'chicoti')]),
 (976, [('uitându', 'uita')]),
 (977, [('atingând', 'atinge')]),
 (978, [('studiind', 'studia')]),
 (992, [('încercând', 'încerca')]),
 (993, [('încercând', 'încerca')]),
 (996, [('închizând', 'închide')]),
 (997, [('tremurând', 'tremura')]),
 (1001, [('ştiind', 'şti')]),
 (1002, [('sclipind', 'sclipi')]),
 (1003, [('sclipind', 'sclipi')]),
 (1004, [('închizând', 'închide')]),
 (1014, [('aşteptând', 'aştepta')]),
 (1027, [('ori-fiindcă', 'ori-fi')]),
 (1028, [('ori-fiindcă', 'ori-fi')]),
 (1029, [('ori-fiindcă', 'ori-fi')]),
 (1030, [('păstrând', 'păstra')]),
 (1034, [('simtindu', 'simti')]),
 (1035, [('simtindu', 'simti')]),
 (1039, [('zâmbind', 'zâmbi'), ('măsurându', 'măsura')]),
 (1040, [('zâmbind', 'zâmbi'), ('măsurându', 'măsura')]),
 (1042, [('ascunzându', 'ascunza')]),
 (1043, [('spunându', 'spune')]),
 (1044, [('spunându', 'spune')]),
 (1048, [('frecându', 'freca')]),
 (1059, [('legănând', 'legăna')]),
 (1060, [('mutându', 'muta')]),
 (1063, [('încercând', 'încerca')]),
 (1073, [('venind', 'veni')]),
 (1085,
  [('lucrând', 'lucra'), ('ascultând', 'asculta'), ('plutind', 'pluti')]),
 (1086,
  [('lucrând', 'lucra'), ('ascultând', 'asculta'), ('plutind', 'pluti')]),
 (1087,
  [('lucrând', 'lucra'), ('ascultând', 'asculta'), ('plutind', 'pluti')]),
 (1088, [('rezemându', 'rezema')]),
 (1095,
  [('atârnând', 'atârna'),
   ('împin-gându', 'împin-ga'),
   ('încercând', 'încerca')]),
 (1096,
  [('atârnând', 'atârna'),
   ('împin-gându', 'împin-ga'),
   ('încercând', 'încerca')]),
 (1097,
  [('atârnând', 'atârna'),
   ('împin-gându', 'împin-ga'),
   ('încercând', 'încerca')]),
 (1098,
  [('atârnând', 'atârna'),
   ('împin-gându', 'împin-ga'),
   ('încercând', 'încerca')]),
 (1101, [('lăsându', 'lăsa')]),
 (1102, [('lăsându', 'lăsa')]),
 (1103, [('clătinându', 'clătina')]),
 (1104, [('lipindu', 'lipi')]),
 (1105, [('lipindu', 'lipi')]),
 (1109, [('scuturând', 'scutura')]),
 (1121, [('atârnând', 'atârna'), ('legănându', 'legăna')]),
 (1122, [('ţinându', 'ţina')]),
 (1131, [('mulţu-mindu', 'mulţu-mi')]),
 (1140, [('evadând', 'evada')]),
 (1151, [('dând', 'da')]),
 (1152, [('dând', 'da')]),
 (1162, [('discutând', 'discuta')]),
 (1164, [('înghesuindu', 'înghesui')]),
 (1168, [('ţinând', 'ţinca')]),
 (1195, [('aplecându', 'apleca')]),
 (1206, [('încruntându', 'încrunta')]),
 (1210, [('plecând', 'pleca')]),
 (1233, [('ţinându', 'ţina')]),
 (1234, [('ţinându', 'ţina')]),
 (1238, [('zâmbindu', 'zâmbi')]),
 (1240, [('crezând', 'crede')]),
 (1254, [('lăsându', 'lăsa')]),
 (1260, [("'când", 'îcânde')]),
 (1271, [('foindu', 'foi')]),
 (1272, [('foindu', 'foi')]),
 (1277, [('folosind', 'folosi')]),
 (1278, [('stând', 'sta')]),
 (1289, [('urcând', 'urca')]),
 (1298, [('părăsindu', 'părăsi')]),
 (1299, [('părăsindu', 'părăsi')]),
 (1300, [('părăsindu', 'părăsi')]),

# Building combined df

In [21]:
adv_part_indices_and_lemmas_df = pd.DataFrame(
    adv_part_indices_and_lemmas, columns=["index", "lemma"]
).set_index("index")

In [22]:
gerunziu_indices_and_words_df = pd.DataFrame(
    gerunziu_indices_and_words, columns=["index", "gerunzius_and_lemmas"]
).set_index("index")

In [23]:
gerunziu_indices_and_words_df

                              gerunzius_and_lemmas
index
8                                [(Văzând, vedea)]
10                          [(alunecând, aluneca)]
11                          [(alunecând, aluneca)]
17                                   [(fiind, fi)]
24     [(plimbându, plimba), (întrebând, întreba)]
...                                            ...
29409                           [(plutind, pluti)]
29410                           [(plutind, pluti)]
29411                           [(plutind, pluti)]
29413                           [(sperînd, sperî)]
29414                           [(sperînd, sperî)]

[12385 rows x 1 columns]

In [24]:
adv_part_indices_and_lemmas_df

        lemma
index
27      hurry
31     wonder
36       find
41       find
56       send
...       ...
29392    make
29396  splash
29400   cause
29405   leave
29407    gaze

[5934 rows x 1 columns]

In [25]:
df = pd.concat(
    [df, adv_part_indices_and_lemmas_df, gerunziu_indices_and_words_df],
    axis=1,
)

In [26]:
df

,1,2,3,4,5,6,7,8,english,lemma,gerunzius_and_lemmas
0,carroll-alenka_v_kraji,Alice was,beginning,to get very tired of sitting by her sister on ...,carroll-alenka_v_kraji,,"Aşezată lângă sora ei, pe malul apei, Alice în...",,Alice was beginning to get very tired of sitti...,NaN,NaN
1,carroll-alenka_v_kraji,Alice was beginning to get very tired of,sitting,"by her sister on the bank , and of having noth...",carroll-alenka_v_kraji,,"Aşezată lângă sora ei, pe malul apei, Alice în...",,Alice was beginning to get very tired of sitti...,NaN,NaN
2,carroll-alenka_v_kraji,Alice was beginning to get very tired of sitti...,having,nothing to do : once or twice she had peeped i...,carroll-alenka_v_kraji,,"Aşezată lângă sora ei, pe malul apei, Alice în...",,Alice was beginning to get very tired of sitti...,NaN,NaN
3,carroll-alenka_v_kraji,Alice was beginning to get very tired of sitti...,reading,", but it had no pictures or conversations in i...",carroll-alenka_v_kraji,,"Aşezată lângă sora ei, pe malul apei, Alice în...",,Alice was beginning to get very tired of sitti...,NaN,NaN
4,carroll-alenka_v_kraji,So she was,considering,", in her own mind ( as well as she could , for...",carroll-alenka_v_kraji,,Şi doar ce era pe punctul de a chibzui (atât c...,,"So she was considering, in her own mind (as we...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
29410,Rushdie-MauruvPosl_Vzd,to the defeated love that is greater than what...,flowing,"together , for putting an end to frontiers , f...",Rushdie-MauruvPosl_Vzd,,"Alhambra, fortul roşu al Europei, fratele celo...",,to the defeated love that is greater than what...,NaN,"[(plutind, pluti)]"
29411,Rushdie-MauruvPosl_Vzd,to the defeated love that is greater than what...,putting,"an end to frontiers , for the dropping of the ...",Rushdie-MauruvPosl_Vzd,,"Alhambra, fortul roşu al Europei, fratele celo...",,to the defeated love that is greater than what...,NaN,"[(plutind, pluti)]"
29412,Rushdie-MauruvPosl_Vzd,The world is full of sleepers,waiting,for their moment of return :,Rushdie-MauruvPosl_Vzd,,Lumea e plină de cei adormiţi care îşi aşteapt...,,The world is full of sleepers waiting for thei...,NaN,NaN
29413,Rushdie-MauruvPosl_Vzd,"and then , like a latter - day Van Winkle , I'...",according,to our family's old practice of falling asleep...,Rushdie-MauruvPosl_Vzd,,"şi apoi, precum un Van Winkle ajuns la bătrîne...",,"and then, like a latter-day Van Winkle, I'll l...",NaN,"[(sperînd, sperî)]"
29414,Rushdie-MauruvPosl_Vzd,"and then , like a latter - day Van Winkle , I'...",falling,"asleep in times of trouble , and hope to awake...",Rushdie-MauruvPosl_Vzd,,"şi apoi, precum un Van Winkle ajuns la bătrîne...",,"and then, like a latter-day Van Winkle, I'll l...",NaN,"[(sperînd, sperî)]"

In [27]:
df["is_adv_participle"] = False
df.loc[~df["lemma"].isna(), "is_adv_participle"] = True

In [28]:
df["has_gerunziu"] = False
df.loc[~df["gerunzius_and_lemmas"].isna(), "has_gerunziu"] = True

In [29]:
df.loc[df["is_adv_participle"] & df["has_gerunziu"]]

,1,2,3,4,5,6,7,8,english,lemma,gerunzius_and_lemmas,is_adv_participle,has_gerunziu
27,carroll-alenka_v_kraji,"before her was another long passage , and the ...",hurrying,down it .,carroll-alenka_v_kraji,,"înaintea ei se întindea un coridor lung, la ca...",,"before her was another long passage, and the W...",hurry,"[(alergând, alerga)]",True,True
31,carroll-alenka_v_kraji,and when Alice had been all the way down one s...,wondering,how she was ever to get out again .,carroll-alenka_v_kraji,,"Şi, după ce-o străbătu în lung şi în lat, înce...",,and when Alice had been all the way down one s...,wonder,"[(încercând, încerca), (întrebându, întrebându)]",True,True
36,carroll-alenka_v_kraji,"However , this bottle was not marked ‘ poison ...",finding,"it very nice , ( it had , in fact , a sort of ...",carroll-alenka_v_kraji,,"Totuşi pe această sticlă nu scria "" Otravă "" ş...",,"However, this bottle was not marked ‘poison,’ ...",find,"[(găsind, găsi)]",True,True
65,carroll-alenka_v_kraji,"It was the White Rabbit returning , splendidly...",muttering,"to himself as he came , ‘ Oh ! the Duchess , t...",carroll-alenka_v_kraji,,"Era, şi de data asta, Iepurele Alb. Nespus de ...",,"It was the White Rabbit returning, splendidly ...",mutter,"[(ţinând, ţinca), (bombănind, bombăni)]",True,True
68,carroll-alenka_v_kraji,"Alice took up the fan and gloves and , as the ...",talking,.,carroll-alenka_v_kraji,,Alice adună de pe jos mănuşile şi evantaiul şi...,,"Alice took up the fan and gloves and, as the h...",talk,"[(spunându, spune)]",True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29389,Rushdie-MauruvPosl_Vzd,When I had brought my story to the X - ray roo...,humming,a talcum - powder shanty .,Rushdie-MauruvPosl_Vzd,,După ce ajunsei cu povestirea la încăperea pli...,,When I had brought my story to the X-ray room ...,hum,"[(zdrăngănindu, zdrăngăni), (ţinînd, ţine), (f...",True,True
29392,Rushdie-MauruvPosl_Vzd,"My breath brayed loudly ,",making,a jackass of me once again .,Rushdie-MauruvPosl_Vzd,,"Respiraţia îmi era ca un nechezat puternic, fă...",,"My breath brayed loudly, making a jackass of m...",make,"[(făcîndu, face)]",True,True
29396,Rushdie-MauruvPosl_Vzd,– Bloodstains spread across the front and rear...,splashing,"in his own , and fatal , pools .",Rushdie-MauruvPosl_Vzd,,-Petele de sînge se întinseră pe partea din fa...,,– Bloodstains spread across the front and rear...,splash,"[(împroşcînd, împroşca)]",True,True
29405,Rushdie-MauruvPosl_Vzd,"I put on my greatcoat , and ,",leaving,"my cell , found the rest of my text in Vasco's...",Rushdie-MauruvPosl_Vzd,,"Îmi îmbrăcai haina şi, ieşind din celulă, găsi...",,"I put on my greatcoat, and, leaving my cell, f...",leave,"[(ieşind, ieşi)]",True,True
29407,Rushdie-MauruvPosl_Vzd,"And so I sit here in the last light , upon thi...",gazing,out across a valley towards a distant hill ;,Rushdie-MauruvPosl_Vzd,,"Aşa că iată-mă-s aici, în lumina acestui amurg...",,"And so I sit here in the last light, upon this...",gaze,"[(privind, privind)]",True,True

In [30]:
df.loc[df["is_adv_participle"] & df["has_gerunziu"]].to_csv("extraction_output/adv_part_with_gerunziu.csv")

In [31]:
len(df)

29415

In [32]:
len(df.loc[df["is_adv_participle"]])

5934

In [33]:
df.to_csv("extraction_output/annotated_all_part_to_ger.csv")

# Assigning adverbial participles to gerunzius

In [35]:
df = pd.read_csv("extraction_output/adv_part_with_gerunziu.csv", index_col=0)

In [36]:
import functions_gensim

In [37]:
for (
    i,
    row,
) in df.iterrows():
    adv_part = row["3"]
    lemma_en = row["lemma"]
    gerunzius_and_lemmas = eval(row["gerunzius_and_lemmas"])
    best_match = functions_gensim.get_best_match(
        word=adv_part,
        lemma=lemma_en,
        candidate_words_and_lemmas=gerunzius_and_lemmas,
        language_word="en",
    )
    df.loc[i, ["best_match", "best_score"]] = best_match[0], best_match[1]

In [38]:
df.to_csv("extraction_output/adv_ger_matches.csv")